### ISSUE TITLE
Query about integrating with third party libraries.

### ISSUE THREAD

**Issue by pavanky** [inducer/pycuda#103]
I am trying to integrate PyCUDA with [arrayfire-python](https://github.com/arrayfire/arrayfire-python) and am having a few issues with context creation.

arrayfire uses the runtime API exclusively and does not deal in cuContexts. Is there a bridge function in PyCUDA that attaches to an existing context instead of creating a new context?

**Comment by inducer** [comment]
There are people who use runtime-based code all the time. Just ask on the mailing list. They'll be able to help. I'll close this for now.
