### ISSUE TITLE
download-examples-from-wiki.py No longer works

### ISSUE THREAD

**Issue by zenlc2000** [inducer/pycuda#104]
The download-examples-from-wiki.py gives the following error output:

downloading  wiki examples from http://wiki.tiker.net/PyCuda/Examples to wiki-examples/...
fetching page list...
Traceback (most recent call last):
  File "download-examples-from-wiki.py", line 19, in <module>
    all_pages = destwiki.getAllPages()
  File "//anaconda/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "//anaconda/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "//anaconda/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "//anaconda/lib/python2.7/xmlrpclib.py", line 1328, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for wiki.tiker.net/?action=xmlrpc2: 301 Moved Permanently>

**Comment by inducer** [comment]
Thanks for the report!

**Comment by mehdi-shiba** [comment]
Sorry for bumping a closed thread, but I'm getting "502 Bad Gateway" errors with download-examples-from-wiki.py script. Is the server down?
`xmlrpclib.ProtocolError: <ProtocolError for wiki.tiker.net/?action=xmlrpc2: 502 Bad Gateway>`

**Comment by inducer** [comment]
Thanks for the note. The wiki has filled with (attempted) spam to such an extent that the process gets killed because it runs out of memory:
```
Wed Nov 23 23:10:08 2016 - *** HARAKIRI ON WORKER 1 (pid: 22464, try: 1) ***
Wed Nov 23 23:10:08 2016 - HARAKIRI: -- wchan> 0
Wed Nov 23 23:10:08 2016 - HARAKIRI !!! worker 1 status !!!
Wed Nov 23 23:10:08 2016 - HARAKIRI [core 0] 4.34.226.253 - POST /?action=xmlrpc2 since 1479960592
Wed Nov 23 23:10:08 2016 - HARAKIRI !!! end of worker 1 status !!!
Wed Nov 23 23:10:09 2016 - DAMN ! worker 1 (pid: 22464) died, killed by signal 9 :( trying respawn ...
Wed Nov 23 23:10:09 2016 - Respawned uWSGI worker 1 (new pid: 25674)
```

I don't have time to clean up the mess currently. I guess this is why we can't have nice things. :/

**Comment by mehdi-shiba** [comment]
Sorry to hear that :(
Thanks for taking the time to check.

**Comment by botzill** [comment]
Hi. I get this issue again, is there smth to fix this ?

Thx.

**Comment by inducer** [comment]
No, this functionality is gone. You'll have to copy-paste them manually, from here:

https://wiki.tiker.net/PyCuda/Examples

**Comment by botzill** [comment]
I see, too bad. Thx @inducer.
