### ISSUE TITLE
gpuarray.copy ignores allocator

### ISSUE THREAD

**Issue by televator** [inducer/pycuda#106]
Thank you so much for pycuda - makes life so much easier.

However, just ran into some weird errors when I used some old pycuda code and ran the tests which used to work.
It kept on giving me `cuMemAlloc failed: out of memory` errors, which never occurred before.
I think I tracked down the issue being in `gpuarray.copy()` which won't pass the allocator to the copy when creating it, eventually using unpooled memory.
Not sure why this issue hasn't popped up before. I am using this in a sum with generator expression which obviously first calls `gpuarray.__add__(0)` which calls copy.

Sorry, I couldn't get my head around a situation where the behavior is intended, so I simply fixed my problem with
`new = GPUArray(self.shape, self.dtype, self.allocator)` 

Cheers

**Comment by inducer** [comment]
Thanks for the patch!
