### ISSUE TITLE
“import pycuda.driver as cuda" gives me an error

### ISSUE THREAD

**Issue by yechaochen** [inducer/pycuda#110]
Recently I try to build the enviroment of caffe and pycuda in my machine.I install pycuda follow the url: [https://wiki.tiker.net/PyCuda/Installation/Linux/Ubuntu](url) .And I run the demo.py in pycuda/examples and it shows an output.I think the installation of pycuda is successful.
And I build the enviroment of caffe and run the examples in caffe successful.
But when I try to run the demo.py and it gives me an error.
`Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    import pycuda.driver as cuda
ImportError: No module named pycuda.driver
`
Can anyone help me to solve it.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

**Comment by yechaochen** [comment]
@inducer I'm a newcomer in github.Can you tell me where I can seek help to solve the problem and how to do it!?
