### ISSUE TITLE
Windows wheel installer has wrong lib paths

### ISSUE THREAD

**Issue by pwalsh0** [inducer/pycuda#113]
setup.py on windows is trying to use linux paths. 

Looks for cuda libs in %CUDA_PATH%\lib64
Should be looking in %CUDA_PATH%\lib\x64

Temporary workaround for windows users:
Copy x64 folder to %CUDA_PATH% and rename to lib64.

**Comment by inducer** [comment]
Thanks for the suggestion!

**Comment by pwalsh0** [comment]
Sorry I don't think that commit fixes it. 
Your fix will add paths: ${CUDA_ROOT}/x64, the correct path is ${CUDA_ROOT}/lib/x64.

Also I forgot to mention some other windows specific flags, please also add these :) 
CXXFLAGS = ['/EHsc']
LDFLAGS = ['/FORCE']

**Comment by inducer** [comment]
Alright, here's the next attempt. :) Let me know if that looks better.

**Comment by pwalsh0** [comment]
Looking good!
