### ISSUE TITLE
Python 3 compatibility issue with OS X

### ISSUE THREAD

**Issue by samkalat** [inducer/pycuda#115]
On a Mac using Python 3.x, PyCUDA will throw an exception in the compiler module when determining the host platform:

`File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pycuda-2016.1.1-py3.4-macosx-10.11-x86_64.egg/pycuda/compiler.py", line 243, in compile
    if 'darwin' in sys.platform and sys.maxint == 9223372036854775807:
AttributeError: 'module' object has no attribute 'maxint'`

The code in question is just looking for maxint, which I suppose is not part of the sys module in Python 3.

`if 'darwin' in sys.platform and sys.maxint == 9223372036854775807:`
`        options.append('-m64')`

There is a pretty simple workaround (on my 64-bit Mac) that has worked for me thus far, and to the extent that I have used PyCUDA there do not seem to be any further problems with Python 3.x:

`import sys`
`sys.maxint = 9223372036854775807`

Thanks for making PyCUDA and PyOpenCL both, they have been terrific.

**Comment by inducer** [comment]
Thanks for the report! It turns out that this has been fixed in git since May: e3864b5f6c15bf0819271f16a40f58a9b784878f. I've just released version 2016.1.2 with this and a few other fixes.
