### ISSUE TITLE
New Features: Interface with NUMPY , CUPY and PYCUDA

### ISSUE THREAD

**Issue by arita37** [inducer/pycuda#117]
Hello,

There is another package called CUPY used for Chainer Deep Learning, and the main difference is
CUPY is natively 1 to 1 matching a subset of NUMPY, which extremely fast /natural the porting of numpy code into GPU running code.
Here, the open source:
http://docs.chainer.org/en/stable/cupy-reference/index.html

https://github.com/pfnet/chainer/tree/ed8ef4786be325899119c3827febc9286da7e354/cupy

Main problem with CUPY, is we need to install the full deep learning package chainer, and long dependencies whereas we have mostly interest only in GPU capabilities.

Questions:

1) Would it be possible to define a sub-package of PYCUDA which match a subset of NUMPY like this:
pycuda.np.sin   == numpy.sin

(with little manual initialization, manual overhead), so compatible GPU can transposed directly from NUMPY code ?

Like CUPY (transpose is done through simple python interface).

2) Only a subset, focus on array computation would be sufficient.
It might some overhead, for the coding would be simplified for many of the models available in NUMPY.

**Comment by inducer** [comment]
It sounds like you're talking about the GPUArray functionality already present in PyCUDA. Closing.
