### ISSUE TITLE
Mapping with CUDA API natively

### ISSUE THREAD

**Issue by arita37** [inducer/pycuda#118]
Hello,

As Nvidia provides a C API and a C++ Layer API for his CUDA framework, and Intel is now supporting directly Python by optimizing CPU for python,
ie below:
Intel Python:  https://software.intel.com/en-us/python-distribution

Would it be possible to get a native mapping from NVIDIA people with Python, particularly PYCUDA
through their C or C++ API ?

It would help to have the new  CUDA API functionnalities easily integrated into Python (hence pycuda).

THanks

**Comment by inducer** [comment]
I'm not sure I understand what you mean. Please feel free to reopen with an explanation.
