### ISSUE TITLE
Layer interface with numpy

### ISSUE THREAD

**Issue by arita37** [inducer/pycuda#120]
Hello,

There is gpu_array to map array of numpy.

But, it would easier/better to have an interface layer of numpy in pycuda,
so numpy code can executed through pycuda naturally with less usage of kernel code,.....

Example:
pycuda.np.initializegpu()

V= np.zeros(5)
X2=pycuda.np.sin(v)

So, all the cuda machinery is enclosed inside pycuda.np.sin
It makes all the sense with unified memory in Cuda 8, all the transfer, compile is behind.

(If people wants to tweak the details, they can use gpuarray instead)

Also, it would enable a stable API interface to build application.

There is another package called CUPY used for Chainer Deep Learning, and the main difference is
CUPY is natively 1 to 1 matching a subset of NUMPY.
Here, the open source:
http://docs.chainer.org/en/stable/cupy-reference/index.html

https://github.com/pfnet/chainer/tree/ed8ef4786be325899119c3827febc9286da7e354/cupy

**Comment by inducer** [comment]
Thanks for your suggestion. What you are suggesting is a whole different software project (an interesting one!), but that is not what PyCUDA is about.

**Comment by arita37** [comment]
Hello,

As you know better the API of PyCUDA, how much difficult to create such module using Pycuda ?
Mainly, a subset of numpy math and array functions ( sum , cumsum, sin,.....)

What would be the tricky parts ?

I may want to start this project for personal needs.

**Comment by inducer** [comment]
IMO, the difficult bit is generating code for all the different combinations of operations that can occur. FWIW, I've created [loopy](https://documen.tician.de/loopy/) as a tool to make that easier.

**Comment by oleg-trott** [comment]
https://github.com/NervanaSystems/nervanagpu (now part of Neon) does that. It can compile rather sophisticated expressions, including multiple reductions on the same axis, into a single kernel.

**Comment by arita37** [comment]
@inducer :  Thanks for your reference, It seems detailed, but still at low level.
because I need to handle a lot other theoretical points for my project (Physics ).

@oleg-trott :
   It seems Nervanna integrated this package into their own Neural System.


    CUPY is similar although much closer to NUMPY syntax:
         cupy.sin(v)         to compute in GPU

    http://docs.chainer.org/en/stable/cupy-reference/generic.html

Nervanna and CUPY have embeds their python GPU engine....., which not make easy to use it
outside of Neural network (for example algorithmic optimization)

CUPY has the advantage to make it generic between numpy and GPU.
Nervanna sounds better in term of optimization process....

Any experience using NevannaGPU outside of Neural Network building ?

Thanks vm.

**Comment by oleg-trott** [comment]
You can use nervanagpu without creating neural networks, much like numpy. Here are some examples: https://gist.github.com/oleg-trott (these were for bug reports)

It doesn't really cater to other uses. For example, it doesn't implement "sin". It would be easy to add it though. 

Neon's project page might be a better place to discuss these topics. 

By the way, some issues carry over to pycuda though. It's my understanding that https://github.com/NervanaSystems/nervanagpu/issues/13 has been reported and fixed? Perhaps others apply to pycuda as well.
