### ISSUE TITLE
PyCUDA needs manual build to work with CUDA 8.0 sdk

### ISSUE THREAD

**Issue by pwalsh0** [inducer/pycuda#124]
As subject, after updating to CUDA 8.0 sdk on linux, pycuda (from PIP) will no longer work - it seems to have a hardcoded dependency on libcurand.so.7.5. Strangely the windows package will pick up the new dlls fine. 

PyCUDA will work fine if built from source with the 8.0 sdk installed (/usr/local/cuda linked to cuda-8.0). 

Should be a simple fix to remove explicit dependency?

**Comment by pwalsh0** [comment]
Oh, and I did try uninstalling/reinstalling pycuda from Pip - hoping it would detect the new SDK and use the correct libraries. But it still was trying to link against libcurand.so.7.5. Only a manual build solved the problem.

**Comment by inducer** [comment]
I have no idea why it would do that. Could you post the build log (for when it breaks)? Also, posting to the mailing list may help get more eyes on this.

**Comment by pwalsh0** [comment]
Err how do I get a build log from pip install? Is it a pre-built binary or does it run setup.py?

**Comment by inducer** [comment]
`pip install` runs `setup.py install`--the two should be mostly equivalent. This is starting to look less like a bug and more like an issue on your end.

This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.
