### ISSUE TITLE
bugs in the test suite - at least for windows

### ISSUE THREAD

**Issue by terrylyons** [inducer/pycuda#126]
I just cleanly installed PyCUDA for my laptop (Win10 Quadro m2100). Python 2.7 with mkl etc.  from the UCI site and with VS2013/Cuda 7.5. 

Installing PyCuda causes the test suite for theano to crash far more quickly than without installation. 

This motivated me to run the test suite for PyCUDA to check all was well. In general it is good and at most a couple of tests fail. But they should not so I report the issues here in case you can change things or tell me what I have done wrong.

1) There is a dependency on Mako (1.0.4) and in consequence MarkupSafe (0.23). I installed the versions mentioned and this removed the error.
2) there is dependency on resource. This is a unix only module. Its presence seems completely superfluous and replacing
```
        import resource
        a = drv.aligned_empty((2**20,), np.float64,
            alignment=resource.getpagesize())
        a_pin = drv.register_host_memory(a)
```
with 

```
        a = drv.aligned_empty((2**20,), np.float64,)
        a_pin = drv.register_host_memory(a)

```
produces a test that works and probably tests more usefully the default alignment

Finally there are a couple of tests that I don't know how to deal with - perhaps others have ideas.

```

================================== FAILURES ===================================
__________________________ TestGPUArray.test_squeeze __________________________

args = (<test_gpuarray.TestGPUArray instance at 0x0000000008114548>,)
kwargs = {}
pycuda = <module 'pycuda' from 'C:\tools\python2\lib\site-packages\pycuda\__init__.pyc'>
ctx = <pycuda._driver.Context object at 0x000000000831E048>
clear_context_caches = <function clear_context_caches at 0x0000000003FD53C8>
collect = <built-in function collect>

    def f(*args, **kwargs):
        import pycuda.driver
        # appears to be idempotent, i.e. no harm in calling it more than once
        pycuda.driver.init()

        ctx = make_default_context()
        try:
            assert isinstance(ctx.get_device().name(), str)
            assert isinstance(ctx.get_device().compute_capability(), tuple)
            assert isinstance(ctx.get_device().get_attributes(), dict)
>           inner_f(*args, **kwargs)

C:\tools\python2\lib\site-packages\pycuda\tools.py:460:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_gpuarray.TestGPUArray instance at 0x0000000008114548>

    @mark_cuda_test
    def test_squeeze(self):
        shape = (40, 2, 5, 100)
        a_cpu = np.random.random(size=shape)
        a_gpu = gpuarray.to_gpu(a_cpu)

        # Slice with length 1 on dimensions 0 and 1
        a_gpu_slice = a_gpu[0:1,1:2,:,:]
        assert a_gpu_slice.shape == (1,1,shape[2],shape[3])
>       assert a_gpu_slice.flags.c_contiguous
E       assert False
E        +  where False = <pycuda.compyte.array.ArrayFlags instance at 0x0000000008114748>.c_contiguous
E        +    where <pycuda.compyte.array.ArrayFlags instance at 0x0000000008114748> = array([[[[  6.76838608e-01,   3.99449558e-01,   6.65258814e-01,\n            2....484468e-01,   8.03725193e-01,   7.96455024e-01,\n            4.34776442e-01]]]]).flags

test_gpuarray.py:808: AssertionError
==================== 1 failed, 59 passed in 97.22 seconds =====================
Press any key to continue . . .
```
Installed modules:
appdirs (1.4.0)
colorama (0.3.7)
decorator (4.0.10)
Mako (1.0.4)
MarkupSafe (0.23)
nose (1.3.7)
nose-parameterized (0.5.0)
numpy (1.11.2+mkl)
pip (8.1.2)
py (1.4.31)
pycuda (2016.1.2+cuda7518)
pytest (3.0.3)
pytools (2016.2.2)
scipy (0.18.1)
setuptools (28.2.0)
six (1.10.0)
Theano (0.8.2)

**Comment by inducer** [comment]
Thanks for the report! The above two commits should address your first two concerns. I believe 25556f43e5450624ed2ef0005693b2969749a2f0 may already have fixed the last one. I'll close this, please reopen it if that didn't do the trick. Also let me know if that fixed things for you. I'll release an updated version once I hear from you.
