### ISSUE TITLE
Tests fail with ImportError _driver.so: undefined symbol

### ISSUE THREAD

**Issue by kambysese** [inducer/pycuda#129]
Trying to get packages including `pycuda-2016.1.2` working in a python 2.7 (Anaconda) environment. Running Ubuntu 1604 with working nvidia driver and CUDA 8. 
I installed pycuda via 

```
 $ git clone http://git.tiker.net/trees/pycuda.git
 $ cd pycuda
 $ ./configure.py --cuda-enable-gl
 $ git submodule update --init
 $ make -j 4
 $ python setup.py install
```
`nosetests` fails with ImportErrors **...anaconda2/lib/python2.7/site-packages/pycuda-2016.1.2-py2.7-linux-x86_64.egg/pycuda/_driver.so: undefined symbol: gibbirish**
The error persists after new anaconda python install, with clean pycuda rebuild; as well as [setting environment](https://wiki.tiker.net/BoostInstallationHowto#LD_LIBRARY_PATH) with  `export LD_LIBRARY_PATH=$HOME/pool/lib:${LD_LIBRARY_PATH}`--although I don't really understand what $HOME/pool/lib means since it doesn't even exist?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.
