### ISSUE TITLE
SVD through scikit-cuda is throwing NoneType Error in pycuda's gpuarray

### ISSUE THREAD

**Issue by hnykda** [inducer/pycuda#130]
Hi, 

I am trying to make SVD work.

After finding out that CULA is just not downloadable and replaced by CuSOLVER, I inferred from [incomplete](http://scikit-cuda.readthedocs.io/en/latest/generated/skcuda.linalg.svd.html#skcuda.linalg.svd) examples that the correct test code might be this:

```
import pycuda.gpuarray as gpuarray
import pycuda.autoinit
import numpy as np
from skcuda.linalg import svd
a = np.random.randn(6, 9) + 1j*np.random.randn(6, 9)
a = np.asarray(a, np.complex64)
a_gpu = gpuarray.to_gpu(a)
u_gpu, s_gpu, vh_gpu = svd(a_gpu, jobu='A', jobvt='A', lib='cusolver')
```

But with that, I am getting this error:
```
Traceback (most recent call last):
  File "demo2.py", line 8, in <module>
    u_gpu, s_gpu, vh_gpu = svd(a_gpu, jobu='A', jobvt='A', lib='cusolver')
  File "/home/hnykdan1/vu/skcuda/scikit-cuda/skcuda/linalg.py", line 187, in svd
    s_gpu = gpuarray.empty(min(m, n), real_type, allocator=alloc)
  File "/home/hnykdan1/vu/skcuda/pycuda/pycuda/gpuarray.py", line 209, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
TypeError: 'NoneType' object is not callable
```

I even built `pycuda` from github repository (2016.1.2), but the error is same as with the one from `pypi`. `scikit-cuda` is also built from repository (right now). Am I doing something wrong?

**Comment by inducer** [comment]
@lebedov might be able to help.

**Comment by hnykda** [comment]
Sorry, my bad. I have to call `skcuda.misc.init()`
