### ISSUE TITLE
Pycuda with CUDA 8.0

### ISSUE THREAD

**Issue by parunach** [inducer/pycuda#136]
I installed the pycuda-2016.1.2-py2.7-linux-x86_64 in our CentOS machine with CUDA 8.0. I have

```
LD_LIBRARY_PATH=/usr/local/cuda/lib64
CUDA_HOME=/usr/local/cuda
```

When I try

`import pycuda.driver as cuda`

I get

`ImportError: libcurand.so.7.5: cannot open shared object file: No such file or directory`

I see that I have libcudart.so.8.0. Can anyone help me with this?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.
