### ISSUE TITLE
The documentation page is 404 now

### ISSUE THREAD

**Issue by Freshield** [inducer/pycuda#141]
Hello, I go to learn the Pycuda these days but I go to the documentation page today and response the 404 error

**Comment by Freshield** [comment]
And there have some link connect to the GitLab, but I can not sign in even I was signed in other page, meanwhile, I also can not find pycuda through the gitlab search

**Comment by inducer** [comment]
I've recently moved the documentation to a different machine. The DNS update should have fully propagated in another day or so. This is the correct information:

```
$ host documen.tician.de
documen.tician.de is an alias for badger.tiker.net.
badger.tiker.net has address 168.235.102.187
badger.tiker.net has IPv6 address 2604:180:2:569::bad8
```

The Gitlab instance you found, while publicly visible, is only for internal development purposes.

**Comment by inducer** [comment]
(But thanks for reporting this issue!)

**Comment by Freshield** [comment]
OK, thank you

**Comment by Freshield** [comment]
But, when I go to badger.tiker.net, also only show the nginx page as attachment
![2017-04-10 15-49-00](https://cloud.githubusercontent.com/assets/15166014/24879581/5bf86800-1e05-11e7-82b8-7c22d9356e49.png)

**Comment by Freshield** [comment]
And http://badger.tiker.net/pycuda is also response 404

**Comment by inducer** [comment]
Sure, that's expected. (That's how virtual hosts work in HTTP.) Your browser would need to send a `Host: documen.tician.de` HTTP header in order for the docs to be served. `Host: badger.tiker.net`itself is shared among many purposes and doesn't have content of its own.

**Comment by Freshield** [comment]
OK...so can I know how to access to the documentation page? I'm sorry, I only have a basic knowledge for the Web part...

**Comment by inducer** [comment]
I've revived the old doc site for the time being. You should be able to access it now.

**Comment by Freshield** [comment]
It works, thank you very much, have a nice day~
