### ISSUE TITLE
undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev

### ISSUE THREAD

**Issue by sesutton** [inducer/pycuda#142]
After successfully installing from pip 'pycuda-2016.1.2' on Fedora 25 when running 'import pycuda.autoinit' I get the following error:

```
/home/sam/anaconda2/lib/python2.7/site-packages/pycuda/autoinit.py in <module>()
      1 from __future__ import absolute_import
----> 2 import pycuda.driver as cuda
      3 
      4 # Initialize CUDA
      5 cuda.init()

/home/sam/anaconda2/lib/python2.7/site-packages/pycuda/driver.py in <module>()
      3 import six
      4 try:
----> 5     from pycuda._driver import *  # noqa
      6 except ImportError as e:
      7     if "_v2" in str(e):

ImportError: /home/sam/anaconda2/lib/python2.7/site-packages/pycuda/_driver.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
```

I have gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC) installed. 
With Cuda toolkit running completely fine on my GeForce GTX 460. I feel it might be a due to conflicitng libc++ and libstdc++ but not sure. Please let me know if there is any other information I can provide to debug the issue!

**Comment by inducer** [comment]
C++5 switched from one C++ ABI to another. The two aren't compatible. One likely issue is that your PyCUDA is compiled with the new ABI, but another component uses the old ABI.

In general though, this issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

**Comment by sesutton** [comment]
Thank you for getting back to me so quickly, I apologize for not noticing the mailing list tech support. Will speak to them if I can't figure it out!
