### ISSUE TITLE
Problem when using mismatched datatype lengths when copying custom datatypes to the device

### ISSUE THREAD

**Issue by tryabin** [inducer/pycuda#144]
I ran into a problem where data wasn't being copied to the device properly when I used a custom datatype. 

I expected the following code to print "test 1 = 1.234000", but it printed "test 1 = 0.000000". 

```python
import numpy as np
import pycuda.driver as cuda_driver
import pycuda.tools
import pycuda.autoinit
from pycuda.compiler import SourceModule


kernelModule = SourceModule(
'''
#include <stdio.h>

typedef struct Test {
    float value;
    int value2;      
} Test;

__global__ void test_function(Test *testArray, int arrayLength) {                         
     
    int totalNumberOfThreads = gridDim.x*gridDim.y*blockDim.x*blockDim.y;
    int step = totalNumberOfThreads;
    
    int posX = threadIdx.x + blockDim.x*blockIdx.x;
    int posY = threadIdx.y + blockDim.y*blockIdx.y;
    int threadNumber = posX + posY*blockDim.x*gridDim.x;
    int start = threadNumber;
    
    for (int i = start; i < arrayLength; i += step) {  
        printf(\"test %d = %f\\n\", i, testArray[i].value);   
    }
}
''')


kernelFunction = kernelModule.get_function('test_function')

testDataType = np.dtype([('value', np.float32),('value2', np.int64)])

testArray = np.zeros(10, testDataType)
testArray['value'][1] = 1.234
gpuDataPointer = cuda_driver.mem_alloc(testArray.nbytes)
cuda_driver.memcpy_htod(gpuDataPointer, testArray)

kernelFunction(gpuDataPointer, np.int32(10), block=(16, 16, 1), grid=(16, 16))

```

However, when I flipped the order of the variables when defining the struct in the SourceModule code the expected result was printed. 

```c
typedef struct Test {
    int value2; 
    float value;
} Test;
```

I was also able to get it to work properly by changing the datatype of "value2" to "int32", so it seems to be related to mismatched variable lengths.

**Comment by fjarri** [comment]
I think I know what is happening. `int` in CUDA is 4-byte long. So if you want a type corresponding to `np.int64`, you need to use `long`. This leads to another problem — the alignments of the numpy array and the array the kernel expects to see will not match, so you will need to align the type explicitly: 

    testDataType = np.dtype([('value', np.float32),('value2', np.int64)], align=True)

**Comment by tryabin** [comment]
Thanks. In my specific situation I actually wanted to use float64 and int32. I added "align=True" when creating the custom data type it worked as expected.
