### ISSUE TITLE
CUDA 9

### ISSUE THREAD

**Issue by sursu** [inducer/pycuda#156]
When will PyCUDA work with CUDA 9?

**Comment by inducer** [comment]
2017.1.1 (released August 9) should work just fine with CUDA 9.

**Comment by sursu** [comment]
@inducer 
I have CUDA 9, Windows 10, Anaconda 5.0 with Python 3.6.
I have installed PyCUDA with:
`pip install C:\Users\sandu\Downloads\pycuda-2017.1.1+cuda8061-cp36-cp36m-win_amd64.whl`
And everything seemed to work fine. I can import pycuda:
`>>> import pycuda` without errors, but I get errors when I try to import `pycuda.autoinit`:
Here is the error:
`>>> import pycuda.autoinit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Anaconda3\lib\site-packages\pycuda\autoinit.py", line 2, in <module>
    import pycuda.driver as cuda
  File "C:\Python\Anaconda3\lib\site-packages\pycuda\driver.py", line 5, in <module>
    from pycuda._driver import *  # noqa
ImportError: DLL load failed: The specified module could not be found.`

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.
