### ISSUE TITLE
Kernel compilation of operators

### ISSUE THREAD

**Issue by loikki** [inducer/pycuda#158]
Hi,

I have been through your code quickly and I have seen that for gpuarray, your are compiling the operator kernels everytime (and therefore, your code can be slower than numpy).

I am thinking about a way to improve it by precompiling a few usual kernels and then compiling the others only the first time they are called. What do you think?

Best,

**Comment by inducer** [comment]
So, there *is* caching going on, so an operator should never be compiled twice. (Plus the binaries are cached.) I've never had this be a major performance issue. Does your application run into performance issues because of this? I'd be grateful for a concrete example.

**Comment by loikki** [comment]
Sorry, I have been through the code too fast. I have some performance issues and though it was coming from it. I will run more test and keep in touch then.

**Comment by loikki** [comment]
Ok perfect, I am able to get a nice speedup curve.

Thank you very much!
