### ISSUE TITLE
_locate_cuda_libdir broken on Debian

### ISSUE THREAD

**Issue by sclarkson** [inducer/pycuda#160]
Introduced in 25e118a

https://github.com/inducer/pycuda/blob/a752768cbcb417d05c9ba12b64ae17c285b27b41/pycuda/compiler.py#L396-L399

Using nvidia-cuda-toolkit from Debian non-free, nvcc is located at `/usr/bin/nvcc`, so this code ends up reporting the libdir as `/usr/bin/../lib64`, bypassing the next few lines that previously correctly reported the libdir as `/usr/lib/x86_64-linux-gnu`

**Comment by inducer** [comment]
Does this proposed fix do the trick for you?

**Comment by inducer** [comment]
(Reopen if not)
