### ISSUE TITLE
GPUArray transpose

### ISSUE THREAD

**Issue by mrader1248** [inducer/pycuda#164]
In comparison to the `numpy.ndarray` class the `GPUArray` class of PyCUDA has no method `transpose`. Are there plans to implement this?

**Comment by inducer** [comment]
Not at this moment, sorry.

**Comment by inducer** [comment]
(unless you submit a patch)

**Comment by mrader1248** [comment]
This is a simple, but working kernel to transpose n-dimensional arrays. I know that there is still room for improvements, but for my needs this would be a sufficient solution. One advantage of this implementation: It can give resulting arrays of arbitrary order. I would look forward to see this kernel integrated into PyCUDA!

```python
import numpy as np
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
from pycuda.compiler import SourceModule

mod = SourceModule("""
__global__ void transpose(
    const float * a, const int * sa, 
    float * b, const int * sb,
    int ndim, int size, 
    const int * axes,
    const int * sborder) {
    
    int j = threadIdx.x + blockIdx.x * blockDim.x;
    if (j < size) {
        
        int j2 = 0;
        int j3 = j;
        
        for (int k = 0; k < ndim; ++k) {
            int k2 = sborder[k];
            int l = j3 / sb[k2];
            j2 += l * sa[axes[k2]];
            j3 -= l * sb[k2];
        }
        
        b[j] = a[j2];
    }
}
""")
gpu_transpose_raw = mod.get_function("transpose")

def gpu_transpose(a_gpu, axes, order="C", blocksize=1024):
    b_gpu = gpuarray.empty(np.array(a_gpu.shape)[axes], a_gpu.dtype, order=order)
    sb_order_gpu = gpuarray.to_gpu(np.asarray(np.argsort(b_gpu.strides)[::-1], np.int32))
    gridsize = int(np.ceil(a_gpu.size/(1.*blocksize)))
    sa_gpu = gpuarray.to_gpu(np.asarray(a_gpu.strides, np.int32) / a_gpu.itemsize)
    sb_gpu = gpuarray.to_gpu(np.asarray(b_gpu.strides, np.int32) / b_gpu.itemsize)
    axes_gpu = gpuarray.to_gpu(np.asarray(axes, np.int32))
    gpu_transpose_raw(
        a_gpu, sa_gpu, b_gpu, sb_gpu,
        np.int32(a_gpu.ndim), np.int32(a_gpu.size),
        axes_gpu, sb_order_gpu,
        block=(blocksize,1,1), grid=(gridsize,1))
    return b_gpu


# note: array a can be of any order
a = np.asarray(np.random.rand(2,3,4,5), np.float32, "F") 
a_gpu = gpuarray.to_gpu(a)
axes = [1,3,2,0]

b_test = a.transpose(axes)

b_gpu = gpu_transpose(a_gpu, axes)
b = b_gpu.get()
print np.allclose(b, b_test)

b_gpu = gpu_transpose(a_gpu, axes, "F")
b = b_gpu.get()
print np.allclose(b, b_test)
```

**Comment by inducer** [comment]
Hmm. [GPUArray.transpose](https://github.com/inducer/pycuda/blob/cfb787ac73a523fe4b32eff31ecffac485388bbf/pycuda/gpuarray.py#L800) actually is implemented. And, to match numpy's semantics, it doesn't do any memory movement. But thanks for submitting your kernel.

**Comment by mrader1248** [comment]
Okay, didn't see this method before, as it's missing in the documentation. But then your implementation of `reshape` doesn't handle transposed arrays correctly and it should use my kernel when the array has been transposed before (the numpy-way). You could as well leave the method `reshape` unchanged and use my kernel in the method `transpose` (the matlab-way).
