### ISSUE TITLE
Using numpy functions inside C++ GPU code

### ISSUE THREAD

**Issue by pbruneau** [inducer/pycuda#165]
Hi all,

This may sound as a dumb question, but asking anyway: as there seems to be a close connection between numpy vectors and parameters in code complied by `SourceModule`, is it possible to use functions from numpy in the latter code? (either transparently, or using a function pointer of some kind)

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
