### ISSUE TITLE
Question: Generate Poisson Rand on the fly?

### ISSUE THREAD

**Issue by sriki18** [inducer/pycuda#176]
Hello,

I am trying to write a Gillespie simulation (with tau leaping) such that each simulation runs on a single thread. This means that I need to generate Poisson distributed random integers over the course of the computation within a single thread. 

Between GPU Arrays + Elementwise Kernels and writing C code for JIT with SourceModule, is it possible to generate Poisson numbers on the fly? My understanding of the cuRAND wrapper is that it can be used to fill up GPU arrays while initializing them. Can it also be used with outside of this?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own. Sorry!
