### ISSUE TITLE
cant multiply 2 matrices of the same size

### ISSUE THREAD

**Issue by itaysason** [inducer/pycuda#177]
Hi, I am having troubles with matrix multiplications because the strides dont match.
Here is a toy example:

> import pycuda.gpuarray as gpuarray
> import pycuda.autoinit
> import numpy as np
> import skcuda.linalg as linalg
> linalg.init()
> a = np.arange(4*4).reshape(4,4).astype('float32')
> b = np.arange(4*4).reshape(4,4).astype('float32')
> b_T = np.transpose(b)
> a_gpu = gpuarray.to_gpu(a)
> b_gpu = gpuarray.to_gpu(b)
> b_T_gpu = gpuarray.to_gpu(b_T)
> ab_gpu = linalg.dot(a_gpu, b_gpu) # this works
> ab_T_gpu = linalg.dot(a_gpu, b_T_gpu) # this fails since the strides order are not compatible

> ValueError:
>  unsupported combination of input order
 
pycuda = 2017.1.1
numpy = 1.14
python = 3.6

**Comment by inducer** [comment]
This looks like a tech support question for scikit cuda. Sorry, wrong tracker.
