### ISSUE TITLE
cant support rtx2070

### ISSUE THREAD

**Issue by AOtrans** [inducer/pycuda#191]
when I compiled pycuda from source, it was all right.
But when I ran command python test_driver.py to verify installing, got this error:
     Value 'sm_75' is not defined for option 'gpu-architecture'

does pycuda not support rtx serial yet?
ps: cuda version is 9.0, cudnn verson is 7.3.1

**Comment by inducer** [comment]
CUDA 9 doesn't support Turing AFAIK. You need CUDA 10.
