### ISSUE TITLE
Tricks to avoid device2device data copy when slicing the gpuarray?

### ISSUE THREAD

**Issue by PeterHuang2015** [inducer/pycuda#194]
Hi All,

@inducer THANK YOU for providing PyCUDA.

As cudaMalloc could be time-consuming, it seems even slicing would include such operation in PyCUDA, are there any tricks to avoid frequent gpu memory operation in PyCUDA?

Regards,
Peter

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

**Comment by inducer** [comment]
Yes, that's the idea.
