### ISSUE TITLE
Allocating arrays greater than 4GB

### ISSUE THREAD

**Issue by rhacking** [inducer/pycuda#197]
Setup: 
- pycuda: 2018.1.1+cuda100, 
- Python 3.6.5 |Anaconda custom (64-bit)| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
- Windows Server 2012 R2 Standard

When I try move an np.ndarray to the gpu as follows:
```python
x = np.random.rand(900, 700, 2000)
gpuarray.to_gpu(x)
```

I get:

```python
C:\ProgramData\Anaconda3\lib\site-packages\pycuda\gpuarray.py in __init__(self,
shape, dtype, allocator, base, gpudata, strides, order)
    208         if gpudata is None:
    209             if self.size:
--> 210                 self.gpudata = self.allocator(self.size * self.dtype.itemsize)
    211             else:
    212                 self.gpudata = None

OverflowError: Python int too large to convert to C unsigned long
```

It appears I can't allocate any arrays larger 4GB. Is there any way to fix this issue?

**Comment by inducer** [comment]
It should be pretty simple to fix. At some point, Nvidia must have changed the interface of `cuMemAlloc` from `unsigned int` to `size_t` (as they should have). The wrapper now just needs to be updated to track this change. I'd be happy to take a PR.

**Comment by majra80** [comment]
Do you know if there any updates on this issue?

**Comment by inducer** [comment]
I tried the code in the first comment (64-bit Linux, CUDA 9, driver 396.54), and it runs for me without an issue.

**Comment by inducer** [comment]
(on a634d2a)

**Comment by lukepfister** [comment]
The code worked for me as well (64 bit linux, CUDA 10.1, driver 418.39).  

I looked at the change you mentioned ('unsigned int'  to 'size_t');  is it as simple as

```diff 
--- a/src/wrapper/wrap_cudadrv.cpp
+++ b/src/wrapper/wrap_cudadrv.cpp
@@ -97,7 +97,7 @@ namespace
 
 
 
-  device_allocation *mem_alloc_wrap(unsigned long bytes)
+  device_allocation *mem_alloc_wrap(size_t bytes)
   {
     return new device_allocation(pycuda::mem_alloc_gc(bytes));
   }
```

Of course, since the original code worked for me, I couldn't verify that this fixed the original issue.

**Comment by inducer** [comment]
Yeah, that looks like a good change to make. I've made a few more analogous changes, here:

https://gitlab.tiker.net/inducer/pycuda/merge_requests/16

**Comment by inducer** [comment]
That just passed CI and is merged now.

**Comment by kyciyas** [comment]
I tried to set 6.4Gb to GPU memory with mem_alloc and faced the same issue.
My system is Windows 10,GPU is GTX 1080Ti and CUDA version 10.0. 
Also I tried with cupy and it was successful.
Could you confirm that this issue is solved for Windows 10 too?

The error message is in the following:
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import pycuda
>>> import pycuda.autoinit
>>> from pycuda import driver as drv
>>> array1 = numpy.zeros((2001,2001,400), dtype = numpy.float32)
>>> cuda_array = drv.mem_alloc(array1.nbytes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C unsigned long

**Comment by inducer** [comment]
Did you build from git?

**Comment by kyciyas** [comment]
> Did you build from git?

No I used pip to install.
pip install pycuda

**Comment by kyciyas** [comment]
> Did you build from git?

May I ask if you can answer the following questions:
1. Is the 4Gb problem is still alive in windows version installed via pip?
2. Are you working on resolving the issue if 1 is Yes?

Many thanks.

**Comment by inducer** [comment]
I just uploaded version 2019.1.1 containing the fix to the package index. Let me know if this addresses your issue.

**Comment by kyciyas** [comment]
> I just uploaded version 2019.1.1 containing the fix to the package index. Let me know if this addresses your issue.

I tested with 6.4Gb array and seems like working fine. Thanks a lot.

**Comment by inducer** [comment]
Happy to hear it. Thanks for letting me know.
