### ISSUE TITLE
cuda.h: No such file or directory

### ISSUE THREAD

**Issue by gionanide** [inducer/pycuda#201]
In file included from src/cpp/cuda.cpp:1:0:
    src/cpp/cuda.hpp:14:10: fatal error: cuda.h: No such file or directory
     #include <cuda.h>
              ^~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by gionanide** [comment]
**Solution** :  

Created a new file in the following directory: /etc/profile.d/cuda.sh  

and add this line:  export PATH=/usr/local/cuda-version/bin:$PATH  

where ''version'', is your Cuda version, you can find this as follows, :  nvcc --version

**example**:  

export PATH=/usr/local/cuda-9.1.85/bin:$PATH

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

**Comment by jiashenC** [comment]
https://github.com/locuslab/pytorch_fft/issues/21#issuecomment-372727363
