### ISSUE TITLE
gpudata attribute of GPUArray.view() set to pointer, not DeviceAllocation 

### ISSUE THREAD

**Issue by lebedov** [inducer/pycuda#202]
GPUArray.view() returns a GPUArray instance, but it appears that the gpudata attribute of the latter is set to the GPU pointer (an int) rather than the DeviceAllocation instance in the original GPUArray instance. Is that behavior intended?

I'm using pycuda 2018.1.1.

**Comment by inducer** [comment]
Yes, I think that's intended. The `.base` attribute is used for keeping the allocation alive, while the pointer needs to move to an address which we can't easily hand to memory allocation. Closing this, reopen and comment if you disagree.
