### ISSUE TITLE
support cuda 10.1 (can't find libcurand.so.10.0)

### ISSUE THREAD

**Issue by dongzhuoer** [inducer/pycuda#204]
```
ImportError: libcurand.so.10.0: cannot open shared object file: No such file or directory
```

I install cuda 10.1, which only provides

```
/usr/local/cuda/lib64/libcurand.so
/usr/local/cuda/lib64/libcurand.so.10
/usr/local/cuda/lib64/libcurand.so.10.1.168
```

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

**Comment by dongzhuoer** [comment]
I think it's indeed a issue

```
ldd ~/.local/lib/python3.7/site-packages/pycuda/_driver.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffca1d99000)
	libcuda.so.1 => /lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f7f07fd1000)
	libcurand.so.10.0 => not found
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7f07df0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7f07dd6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7f07db5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7f07bca000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7f07a7a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7f07a74000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7f07a69000)
	libnvidia-fatbinaryloader.so.418.67 => /lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.418.67 (0x00007f7f0781b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7f0932c000)
```

`_driver.cpython-37m-x86_64-linux-gnu.so` should link to `/usr/local/cuda/lib64/libcurand.so`, a specific version would cause incompatibility.

**Comment by inducer** [comment]
No, sorry. Please read about how shared library versioning works in Linux.

**Comment by dongzhuoer** [comment]
Sorry to trouble you and thanks for you patient guide. I have already solve the problem. 

Here I would brief explain the process in case someone run into a similar situation.

The main cause is that I had install cuda 10.1, then cuda 10.0 (during which I installed pycuda), and reinstall cuda 10.1 again. Though I `pip3 install --force-reinstall pycuda`, pip3 still use the cached wheel. So the solution is `rm -r  .cache/pip/`, [add cuda `bin/` to `PATH`](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#environment-setup), and reinstall pycuda.

**Comment by SahanakaWeerarathna** [comment]
@dongzhuoer thank you very much for your guidance and i was able to solve it with you steps. I previously had cuda 10 and then i switched to cuda10.2 and met this pycuda error and removing cache and force-reinstalling pycuda solve the issue.

**Comment by MuhammadAsadJaved** [comment]
> Sorry to trouble you and thanks for your patient guide. I have already solve the problem.
> 
> Here I would briefly explain the process in case someone run into a similar situation.
> 
> The main cause is that I had install cuda 10.1, then cuda 10.0 (during which I installed pycuda), and reinstall cuda 10.1 again. Though I `pip3 install --force-reinstall pycuda`, pip3 still use the cached wheel. So the solution is `rm -r .cache/pip/`, [add cuda `bin/` to `PATH`](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#environment-setup), and reinstall pycuda.

After 3 hours of struggle , finally the `rm -r .cashe/pip/` , then reinstalling pycuda resolved my issue. Thank you so much.
