### ISSUE TITLE
Optimization level

### ISSUE THREAD

**Issue by jyhmiinlin** [inducer/pycuda#205]
Thanks for the great package. I have been using PyCUDA/PyOpenCL and I get a significant acceleration. 

However, could I control the level of optimization in PyCUDA? I try to look into pycuda.driver.jit_option.OPTIMIZATION_LEVEL but it cannot print the result.

Thanks.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

You can pass options to `SourceModule`.

**Comment by jyhmiinlin** [comment]
Thanks!
