### ISSUE TITLE
ImportError: libcurand.so.10

### ISSUE THREAD

**Issue by agibalov** [inducer/pycuda#206]
Setup:
* Ubuntu 18.04 x64
* Python 3.7.1
* pycuda 2019.1
* CUDA 10.0

This code:
```
import pycuda.driver
```
results in:
```
ImportError: libcurand.so.10: cannot open shared object file: No such file or directory
```
Indeed, I don't have `libcurand.so.10`. I have these:
```
libcurand.so
libcurand.so.10.0
libcurand.so.10.0.130
```
Is it my CUDA installation issue or is something wrong with pycuda's expectations about the environment?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

Try running `ldconfig`, which might create the missing symlink.
(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)

**Comment by agibalov** [comment]
@inducer it's not a support request. I may add "expected result: it works" if it's what would make it a bug report for you.
