### ISSUE TITLE
Reduction Kernel wrong result with custom reduction expression

### ISSUE THREAD

**Issue by Philipp-g** [inducer/pycuda#207]
Example Code to reproduce:
```
f = ReductionKernel(np.float32, "0", "a+2*b", "x[i]+y[i]", "float *x, float *y")
a = np.array([0.5, 0.5])
b = np.array([0.5, 0.5])
a_gpu = gpuarray.to_gpu(a.astype(np.float32))
b_gpu = gpuarray.to_gpu(b.astype(np.float32))
result = f(a_gpu, b_gpu).get()
print(result)
```
result = 6

with ```reduce_expr="2*a+b"```:
result = 768

If I am not misunderstanding the meaning of ```reduce_expr``` I would expect the result to be 3 in both cases.

**Comment by inducer** [comment]
`reduce_expr` must be associative. Neither of your examples satisfy this requirement. This should be made explicit in the docs, which it currently isn't.
