### ISSUE TITLE
Pycuda test_driver.py 26 failed

### ISSUE THREAD

**Issue by Santhosh1509** [inducer/pycuda#208]
OS: Ubuntu 18.04
Device: Jetson Nano
Cuda: 10.0
Python version: 3.6.7
[Installed pycuda as instructed](https://wiki.tiker.net/PyCuda/Installation/Linux)
After 

    sudo make install

Tested using, inside test directory

    python3 test_driver.py

getting this

> ============================================================== warnings summary ==============================================================
> /home/rlpl123/.virtualenvs/test_tensorrt/lib/python3.6/site-packages/_pytest/mark/structures.py:337
>   /home/rlpl123/.virtualenvs/test_tensorrt/lib/python3.6/site-packages/_pytest/mark/structures.py:337: PytestUnknownMarkWarning: Unknown pytest.mark.cuda - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
>     PytestUnknownMarkWarning,
> 
> -- Docs: https://docs.pytest.org/en/latest/warnings.html
> ============================================== 23 failed, 6 passed, 1 warnings in 25.77 seconds ==============================================

What's going wrong?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
