### ISSUE TITLE
Problem using older numpy since pycuda builds against latest

### ISSUE THREAD

**Issue by estan** [inducer/pycuda#209]
Hi @inducer,

First, thanks for your fix for https://github.com/inducer/pycuda/issues/147 so that building occurs after numpy has been installed.

However, we've run into another little snag.

In the log below, I'm attempting:

```
virtualenv -p python3 testenv
source testenv/bin/activate
pip install --no-cache-dir pycuda==2019.1 numpy==1.14.0
```

And then testing with `import pycuda.driver`. This test case is meant to simulate what we do in the requirements.txt of our product - we pin pycuda to 2019.1 and numpy to 1.14.0.

As you can see, it leads to a crash.

The problem is that when the pycuda `setup_requires` dependency of `numpy>=1.6` is satisfied during building of pycuda, it will install the latest numpy version from PyPI (1.16.4) and build against that. This numpy version I believe is installed as a local egg during building.

But the version of numpy (1.14.0) which the user installed is not compatible with the later version (numpy has no guarantee of forward ABI compatibility).

It does however try to maintain backward ABI compatibility within the 1.x series.

If one therefore changes the `setup_requires` of pycuda from

```python
             setup_requires=[
                "numpy>=1.6",
                 ],
```

to

```python
             setup_requires=[
                "numpy==1.6",
                 ],
```

in order to force pycuda to build against exactly 1.6 (the oldest numpy it can build against), to make it compatible with as many numpy versions as possible, I think the problem should go away.

I tried this out and it seems to work. I did however had to use version 1.7 instead of 1.6, because of https://github.com/numpy/numpy/issues/2450 (a problem with installing numpy 1.6 from pip in a virtualenv on Python 3).

So my question is: Would you be OK with changing the `setup_requires` dependency to `numpy==1.7` instead of `numpy>=1.6`. This would ensure the built pycuda will work with any 1.x `numpy` >=1.7 (such as 1.14.0 that we are using).

See also https://github.com/numpy/numpy/issues/5888 which has some discussions about forward/backward ABI compatibility of numpy. The short story I think is that they will try hard to make versions in the 1.x series as compatible as possible, but that they cannot guarantee the forward compatibility case (which is the problem we ran into here).

Full transcript of my test follows below.

```
[estan@newton ~]$ virtualenv -p python3 testenv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/estan/testenv/bin/python3
Also creating executable in /home/estan/testenv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
[estan@newton ~]$ source testenv/bin/activate
(testenv) [estan@newton ~]$ pip install --no-cache-dir pycuda==2019.1 numpy==1.14.0
Collecting pycuda==2019.1
  Downloading https://files.pythonhosted.org/packages/4d/29/5a3eb66c2f1a4adc681f6c8131e9ed677af31b0c8a78726d540bd44b3403/pycuda-2019.1.tar.gz (1.6MB)
     |████████████████████████████████| 1.6MB 11.4MB/s 
Collecting numpy==1.14.0
  Downloading https://files.pythonhosted.org/packages/dc/ac/5c270dffb864f23315e9c1f9e0a0b300c797b3c170666c031c4de42aacae/numpy-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (17.2MB)
     |████████████████████████████████| 17.2MB 19.5MB/s 
Collecting pytools>=2011.2 (from pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/00/96/00416762a3eda8876a17d007df4a946f46b2e4ee1057e0b9714926472ef8/pytools-2019.1.1.tar.gz (58kB)
     |████████████████████████████████| 61kB 52.1MB/s 
Collecting pytest>=2 (from pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/b3/eb/df264c0b1ff4aaf263375dc09aabd9093364f66060be9b26f3a2c166d558/pytest-4.6.3-py2.py3-none-any.whl (229kB)
     |████████████████████████████████| 235kB 30.5MB/s 
Collecting decorator>=3.2.0 (from pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting mako (from pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/0a/af/a6d8aa7b8909a36074f517b15222e3a2fbd5ef3452c0a686e3d43043dd3b/Mako-1.0.12.tar.gz (460kB)
     |████████████████████████████████| 460kB 20.4MB/s 
Collecting six>=1.8.0 (from pytools>=2011.2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting packaging (from pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl (83kB)
     |████████████████████████████████| 92kB 28.0MB/s 
Collecting wcwidth (from pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting atomicwrites>=1.0 (from pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0; python_version > "2.7" (from pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/b3/73/64fb5922b745fc1daee8a2880d907d2a70d9c7bb71eea86fcb9445daab5e/more_itertools-7.0.0-py3-none-any.whl (53kB)
     |████████████████████████████████| 61kB 33.5MB/s 
Collecting attrs>=17.4.0 (from pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12 (from pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/bd/23/dce4879ec58acf3959580bfe769926ed8198727250c5e395e6785c764a02/importlib_metadata-0.18-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/06/ee/de89e0582276e3551df3110088bf20844de2b0e7df2748406876cc78e021/pluggy-0.12.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.9.2 (from mako->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyparsing>=2.0.2 (from packaging->pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl (62kB)
     |████████████████████████████████| 71kB 26.9MB/s 
Collecting zipp>=0.5 (from importlib-metadata>=0.12->pytest>=2->pycuda==2019.1)
  Downloading https://files.pythonhosted.org/packages/a0/0f/9bf71d438d2e9d5fd0e4569ea4d1a2b6f5a524c234c6d221b494298bb4d1/zipp-0.5.1-py2.py3-none-any.whl
Building wheels for collected packages: pycuda, pytools, mako
  Building wheel for pycuda (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-2kfq_act/wheels/de/c2/d5/351a6b47b20d417e82a669cf53f8cb4d7b55a57f73cbd05184
  Building wheel for pytools (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-2kfq_act/wheels/83/df/0b/75ac4572aaa93e3eba6a58472635d0fda907f5f4cf884a3a0c
  Building wheel for mako (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-2kfq_act/wheels/b3/7b/ae/5addd138cd8175503b9782737bada30d0c88310d08c106f9bf
Successfully built pycuda pytools mako
Installing collected packages: decorator, appdirs, six, numpy, pytools, pyparsing, packaging, py, wcwidth, atomicwrites, more-itertools, attrs, zipp, importlib-metadata, pluggy, pytest, MarkupSafe, mako, pycuda
Successfully installed MarkupSafe-1.1.1 appdirs-1.4.3 atomicwrites-1.3.0 attrs-19.1.0 decorator-4.4.0 importlib-metadata-0.18 mako-1.0.12 more-itertools-7.0.0 numpy-1.14.0 packaging-19.0 pluggy-0.12.0 py-1.8.0 pycuda-2019.1 pyparsing-2.4.0 pytest-4.6.3 pytools-2019.1.1 six-1.12.0 wcwidth-0.1.7 zipp-0.5.1
(testenv) [estan@newton ~]$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycuda.driver
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
terminate called after throwing an instance of 'std::runtime_error'
  what():  numpy failed to initialize
Avbruten (SIGABRT) (minnesutskrift skapad)
(testenv) [estan@newton ~]$
```

**Comment by inducer** [comment]
> we pin pycuda to 2019.1 and numpy to 1.14.0.

Can you simply install numpy before you install pycuda? (e.g. by moving numpy above pycuda in your `requirements.txt`?) Then pycuda should build against the correct interface, and your crashes should go away?

**Comment by estan** [comment]
Our current workaround is

```
pip install nympy==<desired version>
pip install -r requirements.txt
```

It is not enough to simply list numpy before pycuda in requirements.txt (in fact, we already do). When pycuda is built it will stilll install the latest numpy anyway (as a local egg I think, brought in through the `setup_requires` during building) and build/link against that.

You can try `pip install --no-cache-dir numpy==1.14.0 pycuda==2019.1` in an empty virtualenv to see this. Importing `pycuda.driver` in that environment will crash due to pycuda being built against a newer numpy.

Typing this on my phone since I'm on the road, so could be wrong, but I'm pretty sure.

**Comment by estan** [comment]
I just tried

```
virtualenv -p python3 testenv
source testenv/bin/activate
pip install numpy==1.14.0 pycuda==2019.1
python3 -c "import pycuda.driver"
```

and the last step still crashes. The problem is the pycuda wheel is built before anything is installed, and at that time, a local install of the latest numpy will be made, and pycuda built/linked against that. And the crash occurs since numpy does not guarantee forward ABI compatibility, so the pycuda built against latest numpy will not run against numpy 1.14.0.

It would work if pycuda was built against an older numpy, e.g. if the `setup_requires` in pycuda was pinned to the oldest numpy against which it can be built (E.g ``==0.7`` probably the best idea considering that old numpy bug I linked to), since numpy maintains backward ABI compatibility.

**Comment by inducer** [comment]
```
pip install --no-cache-dir numpy pycuda==2019.1
```
(note: no `==1.14.0`) succeeds for me without a problem. Another recipe that's likely to succeed is to use two pip calls, one to install numpy, and another to install pycuda. Pinning to an ancient numpy is a nonstarter to me because numpy as recent as 1.11 won't even build on my current crop of systems.

**Comment by estan** [comment]
@inducer Yep, `pip install --no-cache-dir numpy pycuda==2019.1` obviously work, since the version pycuda then builds against and the one that will be installed in the end is the same (latest from PyPI), so there's no compatibility issue then.

And yes, two separate calls to pip works as well, and this is the workaround we're currently using.

This issue is only for when you pin numpy to a version older than the one pycuda is built against, and use either e.g. `pip install --no-cache-dir numpy==<your desired version> pycuda==2019.1`, or a `requirements.txt` like

```
numpy==<your desired version>
pycuda==2019.1
```

In our project, we pin to numpy==1.14.0, which is how we ran into the problem.

I understand if numpy 1.7 won't build on your systems, it will be awkward for you (it built OK here on Ubuntu 18.04, but I didn't test anything else).

Just consider that you're essentially forcing anyone who has `requirements.txt` like

```
numpy==<some version>
pycuda==2019.1
```

to either

1. always set `<some version>` to the latest version of numpy on PyPI, since that's what pycuda will pick up and be built against during the wheel building process (i.e. forcing the user to use the latest numpy version), or
2. Use the 
    ```
    pip install numpy==<some version>
    pip install -r requirements.txt
    ```
    workaround.

It seems reasonable that numpy is always built against the oldest numpy it can be built against, to maintain maximal runtime compatibility with the numpy version the user wants to pin against (which can be older than latest on PyPI).

If 1.7 is too old (won't build on some systems), is there a compromise that could be used? E.g. will 1.13.0 build on your systems? It's reasonably old (2 years), that it's likely most user do not wish to pin their numpy to an older version than that I think (?).

**Comment by inducer** [comment]
It's a pip bug. It should be fixed in pip. (After all, pip ends up ignoring a clear dep specification from the command line that does not contradict what PyCUDA asks.) Hacking around it in PyCUDA is the wrong thing to do, and it will only lead to misery.

In addition, pinning to ancient numpy is a nonstarter for other reasons:

* If you build the virtualenv using `--system-site-packages`, you likely get whatever numpy is installed system-wide, and you can't change it. PyCUDA would be uninstallable in such settings, for no good reason.
* PyCUDA can work against basically any numpy version. Suppose someone else has a good reason to want a later version of numpy. Pinning would inflict misery on them in the same amount that the hack you propose would relieve yours.

**Comment by estan** [comment]
You are right @inducer, I'm convinced by your arguments. It's a pip bug, and I should look up whether it's reported (wouldn't surprise me if it is).

Feel free to close this with WONTFIX and sorry for the noise :)
