### ISSUE TITLE
Swap GPUArray Pointers

### ISSUE THREAD

**Issue by tjburrows** [inducer/pycuda#211]
What would be the proper way to swap pointers of two GPUArrays?  It isn't obvious (to me) since Python doesn't natively support this like C.  Thanks!

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

Swapping `.gpudata` attributes may work, but know it's not a use that's in any way documented or supported. (I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
