### ISSUE TITLE
pagelocked_empty() sometimes uses pageable memory

### ISSUE THREAD

**Issue by renganxu** [inducer/pycuda#217]
I have the following code in my program
```
host_mem = cuda.pagelocked_empty(size, dtype)
```
It allocates buffers for both input and output data. After profiling, I found the program used pinned memory for output correctly, but still used pageable memory for input. The input data is 77.07MB and output is 512B. How could this happen? How to force it to use pinned memory?

**Comment by inducer** [comment]
`pagelocked_empty` is a thin wrapper around [cuMemHostAlloc](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1g572ca4011bfcb25034888a14d4e035b9), so it should behave identically to that function.

**Comment by renganxu** [comment]
@inducer I found the reason. The following is my code (1)
```
self.inputs.host = test_image
cuda.memcpy_htod(self.inputs.device, self.inputs.host)
```
here self.inputs was allocated by pagelocked_empty(), and test_image is the buffer in pageable memory. If I write like this, then the profiling shows it's copying data from pageable memory into GPU memory. It seems self.inputs is just pointing to the test_image buffer without really copying the data.

Now if I change the code into (2):
```
np.copyto(self.inputs.host, test_image)
cuda.memcpy_htod(self.inputs.device, self.inputs.host)
```
Then the profiling shows the data copy from self.inputs.host to self.inputs.device is copying from pinned memory to GPU memory. But we first need to copy the data from pageable memory into pinned memory on the host and this is expensive. 

The time spent on the above two solutions:
(1): 16.6 ms (pageable to GPU memory, although the host buffer was allocated to pinned memory)
(2): 15 ms + 6 ms = 21 ms (pageable to pinned + pinned to GPU memory)

It seems (1) is still better although it didn't copy from pinned memory. Do you know how to move the data from pinned memory to GPU memory and without copying the data from pageable memory to pinned memory?

**Comment by inducer** [comment]
> It seems self.inputs is just pointing to the test_image buffer without really copying the data.

That's how Python works in this setting, yes.
```python
self.inputs.host[:] = test_image
```
would have a similar effect to using `copyto`.

I recommend that all host buffers that are often involved in memory transfers be allocated pinned. If the allocations themselves become a problem, consider using https://documen.tician.de/pycuda/util.html#memory-pool-for-pagelocked-memory.
