### ISSUE TITLE
how to free the pagelocked memory?

### ISSUE THREAD

**Issue by renganxu** [inducer/pycuda#218]
In PyCUDA, we can allocate the pagelocked using the following API:
```
pycuda.driver.pagelocked_empty(shape, dtype, order="C", mem_flags=0)
```
But how to free the allocated memory? I didn't find the corresponding API in PyCUDA

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
https://documen.tician.de/pycuda/driver.html#pagelocked-host-memory
