### ISSUE TITLE
Sending large memory to device with  GPUArray gives "Python int too large to convert to C unsigned long"

### ISSUE THREAD

**Issue by t-tetsuya222** [inducer/pycuda#219]
Hi, I have developed computational fluid dynamics code(Lattice Boltzmann Method) with PyCUDA.
I need to use large memory for large scale calculation.
When I send the Numpy array with shape of (27,500,500,500) to device by gpuarray.to_gpu(arr), PyCUDA gives a following error; "OverflowError: Python int too large to convert to C unsigned long"

I think the memory size of arr is larger than maximum of C unsigned long.
Is there any solution ?

**Comment by inducer** [comment]
That sounds like something that should have been fixed by [this MR](https://gitlab.tiker.net/inducer/pycuda/merge_requests/16). What version are you using?

**Comment by t-tetsuya222** [comment]
Thank you for your response.
My version was "2018.1 ". Now,  updating to the latest version can solve this error.
Thank you!
