### ISSUE TITLE
large size gpuarray arises error

### ISSUE THREAD

**Issue by t-tetsuya222** [inducer/pycuda#220]
Following simple code arise error if I designate large size numpy array such like (27, 500, 500, 500).

//
// sample code start
//

import math  
import numpy as np  
import pycuda.gpuarray as gpuarray  
from pycuda.compiler import SourceModule  
import pycuda.autoinit  
  
module = SourceModule(""" 
__global__ void plus_one_3d(int nx, int ny, int nz, int nv, float *arr){ 
    const int x = threadIdx.x + blockDim.x * blockIdx.x; 
    const int y = threadIdx.y + blockDim.y * blockIdx.y; 
    const int z = threadIdx.z + blockDim.z * blockIdx.z; 
    const int nxyz = nx * ny * z + nx * y + x; 
    int ijk = nx * ny * z + nx * y + x; 
    if (x < nx && y < ny && z < nz){ 
        for (int c = 0; c < nv; c++){ 
            arr[nxyz * c + ijk] += 1.0; 
        } 
    } 
} 
""")  
  
plus_one = module.get_function("plus_one_3d")  
  
num_x, num_y, num_z = np.int32(450), np.int32(450), np.int32(450)  
nv = np.int32(27)  
arr_gpu = gpuarray.zeros([nv, num_z, num_y, num_x], dtype=np.float32)  
  
threads_per_block = (6, 6, 6)  
block_x = math.ceil(num_x / threads_per_block[0])  
block_y = math.ceil(num_y / threads_per_block[1])  
block_z = math.ceil(num_z / threads_per_block[2])  
blocks_per_grid = (block_x, block_y, block_z)  
  
plus_one(num_x, num_y, num_z, nv, arr_gpu, block=threads_per_block, grid=blocks_per_grid)  
  
arr = arr_gpu.get()  
  
print("result :", arr)  

//
// sample code end
//

Debugging with pycharm leads variables "s" is negative of following GPUArray code:

        try:
            s = 1
            for dim in shape:
                s *= dim
        except TypeError:
            # handle dim-0 ndarrays:
            if isinstance(shape, np.ndarray):
                shape = np.asscalar(shape)
            assert isinstance(shape, numbers.Integral)
            s = shape
            shape = (shape,)
        else:
            # handle shapes that are ndarrays
            shape = tuple(shape)

For example, when I desginate arr shape [27, 450, 450, 450], s is -1834592296 instead of 2460375000.

Is there any solution ?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

Your shape entries are numpy scalars of a small size. They shouldn't be if you need them to hold large numbers.
(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
