### ISSUE TITLE
SVD stuck for large Inputs

### ISSUE THREAD

**Issue by khuesmann** [inducer/pycuda#221]
Hi, 

i am trying to calculate SVD using cusolver for large inputs.
My code is the following:

```
import pycuda.autoinit
from pycuda import gpuarray
import numpy as np
from skcuda import linalg, misc

misc.init()

a = np.random.rand(18000, 18000).astype(np.float32)
a_gpu = gpuarray.to_gpu(a)
linalg.init()
U_d, s_d, V_d = linalg.svd(a_gpu,  lib='cusolver')

U = U_d.get()
s = s_d.get()
V = V_d.get()
```
My graphics card is a GeForce 1080TI with CUDA 10.0 . Running this code produces an GPU usage of 100% (nvidia-smi). After a while it dropps to 0%, but the script doesn't terminate. 
Smaller inputs like (2000, 2000) are terminating.

Does anyone have an idea what i am doing wrong??
Thank you very much!!!

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
