### ISSUE TITLE
Allocating managed (unified) memory doesn't seem to work 

### ISSUE THREAD

**Issue by drtpotter** [inducer/pycuda#222]
Hey there,

I'm having problems getting a simple allocation of managed memory to work. Here is my example code and I'm using CUDA 10.1 (GTX1060), with pycuda 2019.1.2 installed through pip and Python 3.7.3.

```python
# Test some arrays
import pycuda.driver as cuda
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import numpy as np

# Parameters
shape=(1024,1024)
float_type=np.float32

# Make a managed array
unified_arr=cuda.managed_empty(shape, float_type, order="C", mem_flags=0)
```
I get this error no matter what I use for shape and dtype.

``
pycuda._driver.LogicError: cuMemAllocManaged failed: invalid argument
``

Thanks for your help with this!

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

You've got to pass a flag to specify memory attachment. (I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)

**Comment by drtpotter** [comment]
Thankyou! It wasn't clear from the documentation that I must provide a flag specifying memory attachment, therefore I thought this was a bug.
