### ISSUE TITLE
pycuda.tools.PageLockedAllocator not exposed

### ISSUE THREAD

**Issue by cf-natali** [inducer/pycuda#227]
Hi,

The documentation mentioned pycuda.tools.PageLockedAllocator:
https://documen.tician.de/pycuda/util.html#pycuda.tools.PageLockedAllocator

But it doesn't seem to be actually exposed:
```
In [18]: pool = pycuda.tools.PageLockedAllocator()
----> 1 pool = pycuda.tools.PageLockedAllocator()

AttributeError: module 'pycuda.tools' has no attribute 'PageLockedAllocator'
```

```
In [21]: pycuda.VERSION
Out[21]: (2019, 1, 2)
```
It seems that there's a missing alias here:
https://github.com/inducer/pycuda/blob/f3a3b71048407f7f30b802a5aa21cf100021128f/pycuda/tools.py#L42

```
DeviceMemoryPool = _drv.DeviceMemoryPool
PageLockedMemoryPool = _drv.PageLockedMemoryPool
```

Adding `PageLockedAllocator = _drv.PageLockedAllocator` should work.

**Comment by inducer** [comment]
Thanks for reporting this, and for your PR! I actually didn't even spot the PR until it was too late and created my own, equivalent version:

https://gitlab.tiker.net/inducer/pycuda/merge_requests/20

Once CI passes, this will go in right away. I'll close your PR (sorry, and thanks again!).

**Comment by cf-natali** [comment]
Cheers!
