### ISSUE TITLE
Does PyCuda supports multiple GPU devices?

### ISSUE THREAD

**Issue by Narasimha1997** [inducer/pycuda#230]
I want to make use of multiple GPUs in a single Python program, I am not running any computations though. I just want to allocate chunks of memory across multiple GPU. I did not find any suitable documentation for this. Is there any way to achieve this ? One way I think is to create multiple contexts and use push() and pop() to activate and deactivate them. Does this retain the state of the context ? 

I also request for a documentation regarding usage of multiple GPUs using PyCuda.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

Don't use `autoinit`, create multiple contexts manually. (I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
