### ISSUE TITLE
 _PyType_Lookup: Assertion `!PyErr_Occurred()' failed.

### ISSUE THREAD

**Issue by sclarkson** [inducer/pycuda#233]
When compiling PyCUDA against a debug build of Python 3.8, I encountered the following error.

```
$ python3.8-dbg -c "import pycuda.autoinit"
python3.8-dbg: ../Objects/typeobject.c:3123: _PyType_Lookup: Assertion `!PyErr_Occurred()' failed.
Aborted (core dumped)
```
This commit from upstream boost fixed the problem. https://github.com/boostorg/python/commit/4f6d547c0af4c400dc5d059ccd847426ff21852f

**Comment by inducer** [comment]
Thanks for the report and for finding a workaround! https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/22
