### ISSUE TITLE
[Documentation] 404 for link to installation instructions 

### ISSUE THREAD

**Issue by ericdoerheit** [inducer/pycuda#239]
Thank you for maintining this CUDA wrapper lib.

Unfortunately, the link provided in the documentation (https://documen.tician.de/pycuda/install.html) to the installation instructions returns an 404 error:
https://wiki.tiker.net/PyCuda/Installation

**Comment by inducer** [comment]
Thanks for letting me know. I migrated my Wiki last weekend, and this apparently didn't get migrated properly. Should be all better now.
