### ISSUE TITLE
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid argument

### ISSUE THREAD

**Issue by zhuhefighting** [inducer/pycuda#241]
When I use the API 'cuda.memcpy_htod_async' , then I meet this error: pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid argument.
How can I fix it ?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

When you do contact the list, please supply a working code example of the problem you're encountering.
