### ISSUE TITLE
Is any api is equal to cuda.set_device(device_id)

### ISSUE THREAD

**Issue by fromwhzz** [inducer/pycuda#243]
I need to set device for the thread, and the thread will call c++ SDK which run gpu-operation.
I need to set the device to let the SDK to run in the device id gpu.
But I check the api, there is no api for me to set device operation.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

https://documen.tician.de/pycuda/driver.html#pycuda.driver.Device.retain_primary_context
(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
