### ISSUE TITLE
Download-examples-from-wiki.py has ProtocolError

### ISSUE THREAD

**Issue by bdlabitt** [inducer/pycuda#245]
Ubuntu 20.04, python 3.8.5, ipython 7.13.0.
Recommendation is to use this program to down load examples.  However it fails with a ProtocolError.  
`In [22]: run download-examples-from-wiki.py                                     
downloading  wiki examples from http://wiki.tiker.net/PyCuda/Examples to wiki-examples/...
fetching page list...
---------------------------------------------------------------------------
ProtocolError                             Traceback (most recent call last)
~/Documents/python/pycuda-wiki-examples/download-examples-from-wiki.py in <module>
     16 print("downloading  wiki examples from http://wiki.tiker.net/PyCuda/Examples to wiki-examples/...")
     17 print("fetching page list...")
---> 18 all_pages = destwiki.getAllPages()
     19 
     20 

/usr/lib/python3.8/xmlrpc/client.py in __call__(self, *args)
   1107         return _Method(self.__send, "%s.%s" % (self.__name, name))
   1108     def __call__(self, *args):
-> 1109         return self.__send(self.__name, args)
   1110 
   1111 ##

/usr/lib/python3.8/xmlrpc/client.py in __request(self, methodname, params)
   1448                         allow_none=self.__allow_none).encode(self.__encoding, 'xmlcharrefreplace')
   1449 
-> 1450         response = self.__transport.request(
   1451             self.__host,
   1452             self.__handler,

/usr/lib/python3.8/xmlrpc/client.py in request(self, host, handler, request_body, verbose)
   1151         for i in (0, 1):
   1152             try:
-> 1153                 return self.single_request(host, handler, request_body, verbose)
   1154             except http.client.RemoteDisconnected:
   1155                 if i:

/usr/lib/python3.8/xmlrpc/client.py in single_request(self, host, handler, request_body, verbose)
   1181         if resp.getheader("content-length", ""):
   1182             resp.read()
-> 1183         raise ProtocolError(
   1184             host + handler,
   1185             resp.status, resp.reason,

ProtocolError: <ProtocolError for wiki.tiker.net/?action=xmlrpc2: 405 Not Allowed>

In [23]:                                                                                    
`
Same error if directly called from python3.
`$ python3 download-examples-from-wiki.py
downloading  wiki examples from http://wiki.tiker.net/PyCuda/Examples to wiki-examples/...
fetching page list...
Traceback (most recent call last):
  File "download-examples-from-wiki.py", line 18, in <module>
    all_pages = destwiki.getAllPages()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1183, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for wiki.tiker.net/?action=xmlrpc2: 405 Not Allowed>
`

**Comment by inducer** [comment]
Thanks for the report. That wiki functionally no longer exists. I've simply converted the examples to Python and added them to the git tree.
