### ISSUE TITLE
Option '--cubin (-cubin)' is not allowed when compiling for a virtual compute architecture

### ISSUE THREAD

**Issue by jswudi** [inducer/pycuda#252]
Hi, I am testing PyCuda application using CUDA8 on NVIDIA V100 GPU. To make the application forward compatible, I need to set arch and code options in SourceModule like below:

```
    from pycuda.compiler import SourceModule
    mod = SourceModule("""
    __global__ void multiply_them(float *dest, float *a, float *b)
    {
        const int i = threadIdx.x;
        dest[i] = a[i] * b[i];
    }
    """,
    arch="compute_52",
    code="compute_52")
```

However, I got the error that says

```
[command: nvcc --cubin -arch compute_52 -code compute_52 -I/usr/local/lib/python3.7/site-packages/pycuda/cuda kernel.cu]
[stderr: nvcc fatal : Option '--cubin (-cubin)' is not allowed when compiling for a virtual compute architecture
```

It looks like we cannot specify `--cubin` when set `-arch compute_xx` for virtual compute architecture. However, in pycuda source code, cubin  is hardcoded. It will always run `nvcc --cubin ...` 
1. https://github.com/inducer/pycuda/blob/master/pycuda/compiler.py#L228
2. https://github.com/inducer/pycuda/blob/7dfe1d07b8e4e538bdebe7ab354d0a8dcc0ff9ef/pycuda/compiler.py#L129

How can I remove --cubin option?

**Comment by inducer** [comment]
> To make the application forward compatible

What do you mean? Can't you just ship the source and compile just-in-time on whatever architecture is present?

> for virtual compute architecture

Why not set `-arch sm_XY`?

**Comment by jswudi** [comment]
Figured it out, I need to use DynamicSourceModule and set arch="compute_35" and code="compute_35" for JIT compilation.
