### ISSUE TITLE
PointerHolderBase doesn't work?

### ISSUE THREAD

**Issue by bmerry** [inducer/pycuda#254]
I can't seem to get PointerHolderBase to work as I expected. Here's a simple example where I'm just applying trivial wrapping of DeviceAllocation (in my actual use case, I want to offset the pointer for alignment purposes). I've thrown in an `__int__` just for good measure but it didn't help.

```python
#!/usr/bin/env python3

import pycuda.autoinit
import pycuda.driver
import pycuda.gpuarray
import numpy as np

class WrappedAllocation(pycuda.driver.PointerHolderBase):
    def __init__(self, wrapped):
        self.wrapped = wrapped

    def get_pointer(self):
        return int(self.wrapped)

    def __int__(self):
        return int(self.wrapped)

alloc = WrappedAllocation(pycuda.driver.mem_alloc(1024))
gpuarray = pycuda.gpuarray.GPUArray((1024,), np.uint8, gpudata=alloc)
print(gpuarray.get())
```

It crashes with
```
Traceback (most recent call last):
  File "pycuda-pointer-holder.py", line 20, in <module>
    print(gpuarray.get())
  File "/home/bmerry/work/sdp/env3/lib/python3.8/site-packages/pycuda/gpuarray.py", line 305, in get
    _memcpy_discontig(ary, self, async_=async_, stream=stream)
  File "/home/bmerry/work/sdp/env3/lib/python3.8/site-packages/pycuda/gpuarray.py", line 1309, in _memcpy_discontig
    drv.memcpy_dtoh(dst, src.gpudata)
Boost.Python.ArgumentError: Python argument types in
    pycuda._driver.memcpy_dtoh(numpy.ndarray, WrappedAllocation)
did not match C++ signature:
    memcpy_dtoh(pycudaboost::python::api::object dest, unsigned long long src)
```

I'm using pycuda 2020.1 (also saw it with 2019.1.2), CUDA 11.0, Python 3.8.5.

**Comment by inducer** [comment]
Thanks for reporting this. #256 is my current best attempt. I added your MWE as a test. I don't know why the `implicitly_convertible` to `CUdevptr` doesn't work, when it seems to work for the other types. It'd be awesome if you could give this a try.

**Comment by bmerry** [comment]
I'm also confused why the implicitly_convertible doesn't work, although it's been a long time since I used Boost.Python. 

Unfortunately the branch still doesn't work for me, and the new unit test fails (currently because it's using the wrong names for the imports, but if I fix that it fails with the same error I reported in this bug.

Does it work for you? If so maybe we should check whether it's something related to my system e.g. Boost Python library version?

**Comment by inducer** [comment]
> Does it work for you?

It doesn't. I ran out of time trying to get it to go.

**Comment by bmerry** [comment]
Aha, I figured it out! I was missing a call to `super().__init__()` in the constructor of my wrapper class, which presumably is necessary to trigger Boost to construct the C++ class. Here's a working example:

```python
#!/usr/bin/env python3

import pycuda.autoinit
import pycuda.driver
import pycuda.gpuarray
import numpy as np

class WrappedAllocation(pycuda.driver.PointerHolderBase):
    def __init__(self, wrapped):
        super().__init__()
        self.wrapped = wrapped

    def get_pointer(self):
        return int(self.wrapped)

alloc = WrappedAllocation(pycuda.driver.mem_alloc(1024))
gpuarray = pycuda.gpuarray.GPUArray((1024,), np.uint8, gpudata=alloc)
print(gpuarray.get())
```

That's really an error in my code, but it might be nice to have a warning in the docs for PointerHolderBase. Let me know if you'd like me to write something.

I do like the fact that your branch adds `__int__` for PointerHolderBase, and of course making the converter `const` looks like a good idea too.

**Comment by inducer** [comment]
> it might be nice to have a warning in the docs for PointerHolderBase. Let me know if you'd like me to write something.

I agree. I'd be happy to look at a PR.

> Aha, I figured it out! I was missing a call to `super().__init__()` in the constructor of my wrapper class,

Nice catch! I've updated #256.

**Comment by inducer** [comment]
#256 was (effectively) merged, fixing this.
