### ISSUE TITLE
undefined symbol: cuDevicePrimaryCtxRelease_v2

### ISSUE THREAD

**Issue by zuzhaoye** [inducer/pycuda#255]
Thank you for creating this PyCuda package. I found an issue after the installation while

```
$ cd pycuda-2020.1/test
$ python test_driver.py
```

Got error:
```
ImportError: /home/[my machine name]/anaconda3/envs/[my virtual env name]/lib/python3.7/site-packages/pycuda/_driver.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cuDevicePrimaryCtxRelease_v2
```

I am using Ubuntu 18.04 and having cuda-11.1. What could be the possible cause of this issue? Thx!

**Comment by inducer** [comment]
Your PyCuda was compiled against headers that don't match the rest of your CUDA environment. Did you download a binary?
