### ISSUE TITLE
error: use of undeclared identifier 'cuDevicePrimaryCtxRelease'

### ISSUE THREAD

**Issue by ilciavo** [inducer/pycuda#260]
For debugging purposes, I'm using a gpu with computing capability 1.1. 
Compiling `pycuda-2020`, the function `cuDevicePrimaryCtxRelease`  called in `cuda.hpp` is not found. I looking at the version `pycuda-2014` but this section is not included.
I managed to build and install commenting it out.

```
  class primary_context : public context
  {
   protected:
      CUdevice m_device;

    public:
      primary_context(CUcontext ctx, CUdevice dev)
        : context (ctx), m_device(dev)
      { }

    protected:
      virtual void detach_internal()
      {
        // Primary context comes from retainPrimaryContext.
        //CUDAPP_CALL_GUARDED_CLEANUP(cuDevicePrimaryCtxRelease, (m_device));

      }
  };
```
Should I leave it commented out or use a different function?

**Comment by inducer** [comment]
It looks like that functionality just needs an `#ifdef` for the CUDA version for which it was introduced. I looked at the [docs](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__PRIMARY__CTX.html#group__CUDA__PRIMARY__CTX_1gd779a84f17acdad0d9143d9fe719cfdf). It's not clear at what CUDA version it was introduced. Do you have a sense?

**Comment by ilciavo** [comment]
That function was not part of versions 6.0 and 6.5, but I see it's part of 7.5.
I think I should just add 
```
#if CUDAPP_CUDA_VERSION >= 7000
        CUDAPP_CALL_GUARDED_CLEANUP(cuDevicePrimaryCtxRelease, (m_device));
#endif
```
Thanks
