### ISSUE TITLE
[Documentation] Document memset_*_async

### ISSUE THREAD

**Issue by bmerry** [inducer/pycuda#266]
It looks like PyCUDA provides functions like memset_d8_async, but they're not documented [here](https://documen.tician.de/pycuda/driver.html?highlight=memset_d8#pycuda.driver.memset_d8).

**Comment by inducer** [comment]
Could you submit a PR?

**Comment by inducer** [comment]
(And thanks for the report btw!)

**Comment by bmerry** [comment]
> Could you submit a PR?

Done

> (And thanks for the report btw!)

You're welcome. I was just happy that I had to discard my draft feature request bug and write a documentation issue instead :-)
