### ISSUE TITLE
nvcc compilation failes : unsupported (any more) parameter -arch sm_30.

### ISSUE THREAD

**Issue by muarvyn** [inducer/pycuda#272]
I have tried to run an example from the page https://documen.tician.de/pycuda/tutorial.html.
It is failed with an error:
`CompileError: nvcc compilation of /tmp/tmpwtsurb7b/kernel.cu failed
[command: nvcc --cubin -arch sm_30 -I/home/vlad/.local/lib/python3.8/site-packages/pycuda/cuda kernel.cu]
[stderr:
nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
]`
Some environment details:
`nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0`

[GPU.txt](https://github.com/inducer/pycuda/files/6083983/GPU.txt)

Expected result: No a compile error while running the example for such a configuration.

**Comment by inducer** [comment]
This sounds to me like your GPU might be too old to be supported by your nvcc. (What pycuda does is grab the "compute capability" from the GPU (3.0 in your case) and pass it on (as the `-arch sm_30` flag) to nvcc.) 

Are you able to compile and run examples from the CUDA SDK, e.g. this one: https://github.com/NVIDIA/cuda-samples/tree/master/Samples/matrixMul? If not, a possible remedy might be to install an older version of the CUDA toolkit.

**Comment by muarvyn** [comment]
Thank you for a rapid answer!
You are right, that CUDA installation is unable to run a sample correctly on my GPU. Installing CUDA 10.2 has solved the problem.
Thanx. 
To close this issue.
