### ISSUE TITLE
[Performance] NumPy vs PyCuda

### ISSUE THREAD

**Issue by redradist** [inducer/pycuda#273]
I've tried the simplest example for comparing performance of numpy and pycuda:
```python
import timeit

import pycuda.autoinit
import pycuda.driver as drv
import numpy

from pycuda.compiler import SourceModule


def main():
    mod = SourceModule("""
    __global__ void multiply_them(float *dest, float *a, float *b)
    {
      const int i = threadIdx.x;
      dest[i] = a[i] * b[i] + (a[i] + b[i]) / 3;
    }
    """)

    multiply_them = mod.get_function("multiply_them")

    a = numpy.random.randn(1000).astype(numpy.float32)
    b = numpy.random.randn(1000).astype(numpy.float32)

    dest = numpy.zeros_like(a)

    start_time = timeit.default_timer()
    dest2 = a * b + (a + b) / 3
    print("CPU time difference is :", timeit.default_timer() - start_time)

    start_time = timeit.default_timer()
    multiply_them(
        drv.Out(dest), drv.In(a), drv.In(b),
        block=(1000, 1, 1), grid=(1, 1))
    print("GPU time difference is :", timeit.default_timer() - start_time)


if __name__ == '__main__':
    main()
```
And results are the following:
```console
CPU time difference is : 3.140000000001475e-05
GPU time difference is : 0.001933100000000021
```

I suspect that this happens due to overhead of coping memory from host to device and back ...

Is there some example that could show performance greater than numpy ?
I think that performance would be better for chained operations, but anyway some example would be nice to have ...

**Comment by inducer** [comment]
Unfortunately, I can't teach you performance modeling or proper performance measurement in this comment box (I have taught a class on it, materials [here](https://relate.cs.illinois.edu/course/cs598apk-f18/) if you're curious), but I'd like to emphasize two things:

* The impact of data transfer can be modeled in terms of sizes and bandwidths. It can also be measured, and the measurements should match that prediction. If you need to transfer data back and forth, I think it is good practice to estimate this impact before beginning to write code.
* The expected cost of the kernel you show can likewise be modeled (it should wind up "bandwidth-bound") and measured.

For all intents and purposes, PyCUDA should perform identically to CUDA-C program. If it doesn't, collect data, and report a bug.

Hope that helps at least a bit.

**Comment by redradist** [comment]
@inducer I was not asking to teach me how to write performant kernel, but to provide good example that later could be added to documentation as well ;)
