### ISSUE TITLE
pycuda._driver.Error: cuInit failed: unknown error

### ISSUE THREAD

**Issue by sangwz** [inducer/pycuda#276]
Enviament: WSL, Ubuntu 18, And I make sure my cuda is connected.
![image](https://user-images.githubusercontent.com/58506571/111479563-0da3fa00-876c-11eb-9e38-7f25bdcdc649.png)
nvidia-smi:
![image](https://user-images.githubusercontent.com/58506571/111479710-30361300-876c-11eb-86b7-0dee063a3a40.png)

I got an error when I use the pycuda. There is no error when I input such code
![image](https://user-images.githubusercontent.com/58506571/111478984-8b1b3a80-876b-11eb-86b8-33e8405403cc.png)
And then I use the command `sudo nvidia-modprobe -u` and reboot my device, It doesn't work.
What should I do?

**Comment by inducer** [comment]
What is the error message?

**Comment by sangwz** [comment]
> What is the error message?


cuda.init()
pycuda._driver.Error: cuInit failed: unknown error
![image](https://user-images.githubusercontent.com/58506571/111556645-014c8b00-87c6-11eb-9dd2-5b24bfaac483.png)

**Comment by inducer** [comment]
Are yo able to run driver API CUDA examples, e.g. [this one](https://github.com/NVIDIA/cuda-samples/tree/master/Samples/matrixMulDrv)?

**Comment by sangwz** [comment]
Yes, and I got such result:
![image](https://user-images.githubusercontent.com/58506571/111563739-7d010480-87d3-11eb-8165-24c50e4a1b4c.png)

**Comment by inducer** [comment]
Could you use `ldd` to check whether `./matrixMulDrv` and the result of `python -c 'import pycuda._driver as drv; print(drv.__file__)' ` link to the same `libcuda.so`?

**Comment by sangwz** [comment]
The reult:
![image](https://user-images.githubusercontent.com/58506571/111566777-c1db6a00-87d8-11eb-8287-89e821d80997.png)
![image](https://user-images.githubusercontent.com/58506571/111566934-11ba3100-87d9-11eb-951a-1da0560dc8e9.png)

**Comment by sangwz** [comment]
I find that my WSL has installed the cuda9.1 ，but I don't know when and how, maybe when I install the pycuda a few days ago. 
I can't makeit by `pip install pycuda`， so I found a method what I don't clearly remember to install it. Shoud I uninstall the cuda 9.1?
![image](https://user-images.githubusercontent.com/58506571/111568721-3368e780-87dc-11eb-88e2-f60256e9af3e.png)

**Comment by inducer** [comment]
Run ldd on the `.so` that the `python` command printed.

**Comment by sangwz** [comment]
> Run ldd on the `.so` that the `python` command printed.

![image](https://user-images.githubusercontent.com/58506571/111573001-a5452f00-87e4-11eb-8a5d-2facf3b64af5.png)

**Comment by inducer** [comment]
Clearly both are using the same `libcuda.so.1`, but one causes an error when calling `cuInit`, but the other doesn't? That doesn't make a great deal of sense. Can you be more precise about what's different when `pycuda.init()` succeeds?

**Comment by sangwz** [comment]
> Clearly both are using the same `libcuda.so.1`, but one causes an error when calling `cuInit`, but the other doesn't? That doesn't make a great deal of sense. Can you be more precise about what's different when `pycuda.init()` succeeds?

There is nothing special , it succeeds when I test the code where error occurs, see the [picture](https://github.com/inducer/pycuda/issues/276#issuecomment-801533022), 
``` python
import pycuda.driver as cuda
 cuda.init()
``` 
and there is no error.

**Comment by inducer** [comment]
Then what's different when the error does occur?

**Comment by sangwz** [comment]
> Then what's different when the error does occur?

Thank you ,I think I have solved this problem by reinstall pycuda, And I uninstalled the cuda-9.1.
