### ISSUE TITLE
Which Python versions are supported?

### ISSUE THREAD

**Issue by jakirkham** [inducer/pycuda#279]
In the trove classifiers it looks like Python 2 and some older version of 3 are supported

https://github.com/inducer/pycuda/blob/217fe8e8317a280cf703647d5814e7a6df463c64/setup.py#L214-L218

Though `python_requires` seems to imply Python 3.6 or later

https://github.com/inducer/pycuda/blob/217fe8e8317a280cf703647d5814e7a6df463c64/setup.py#L229

Which is correct? Also would be possible to update the other one to match?

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/48

**Comment by inducer** [comment]
(On Gitlab because that's where actual CI lives... GPUs)

**Comment by jakirkham** [comment]
LGTM. Thanks :)

(not sure how to comment over there)

**Comment by inducer** [comment]
https://github.com/inducer/pycuda/commit/29466d4e93ec20a81ce2534327aed24903c3a2e2

**Comment by jakirkham** [comment]
Great thanks so much Andreas! 😄
