### ISSUE TITLE
DeviceMemoryPool limited to 2**32 bytes (4GB)

### ISSUE THREAD

**Issue by vincefn** [inducer/pycuda#282]
Working with arrays larger than 4 GB leads to a memory error when using a DeviceMemoryPool (`cuMemcpyHtoD failed: invalid argument`). The allocation itself (without a pool) is not a problem above 4GB. Tested under debian9/x86_64 (P6000) and ubuntu20.04/ppc64le with a V100.

A simple test:
``` python
import pycuda.autoinit
import pycuda.gpuarray as cua
import pycuda.tools as cut
import numpy as np

m = cut.DeviceMemoryPool()

a= np.ones(2**30-1,dtype=np.float32)
b= cua.to_gpu(a, allocator=m.allocate)  # Passes

a= np.ones(2**30,dtype=np.float32)
b= cua.to_gpu(a, allocator=m.allocate)  # Error: cuMemcpyHtoD failed: invalid argument
```
This is going to to become a more frequent issue as data sizes grow along with the cards memory.

The reason seems to be the use of boost' Allocator::size_type which apparently maps to uint32. However given how intricate boost headers are, I failed to find exactly where that is defined, so I am not sure how to tackle this issue. 

@inducer I'd be happy to work on a PR but I'd really need some pointers where to search for the origin of `size_type`. Also, is the boost subset up-to-date ?

**Comment by vincefn** [comment]
After removing the use of a pool for that particularly large array I got a similar error:
``` python
cu_drv.memcpy_dtod(dest=dest.gpudata, src=src.gpudata, size=cdi._cu_obj.nbytes)

OverflowError: bad numeric conversion: positive overflow
```

This works if the byte size is <2**32.

**Comment by inducer** [comment]
`Allocator::size_type` comes from [here](https://github.com/inducer/pycuda/blob/29466d4e93ec20a81ce2534327aed24903c3a2e2/src/wrapper/mempool.cpp#L25), which makes it a `size_t`, which should make it 64-bit.

A few of the memcpys that you use were stuck on 32-bit though, https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/49 should address that.

**Comment by inducer** [comment]
I'm guessing that MR should have addressed your issues (merged now). If not, let me know/reopen here.

**Comment by vincefn** [comment]
Hi Andreas - thanks for the quick answer. I confirm that the memcpy issues are fixed.

However the `cua.to_gpu(a, allocator=m.allocate)` code above is not, and still gives a `cuMemcpyHtoD failed: invalid argument`.

I tested further and the issue is not directly with the pool allocation, since:
       `cua.zeros(2**30,dtype=np.float32,allocator=m.allocate)` 
 (with m a `DeviceMemoryPool`) works. I checked the sizeof the size_type and it is indeed 8.

Now reproducing what happens inside `to_gpu()`:
``` python
import pycuda.autoinit
import pycuda.gpuarray as cua
import pycuda.tools as cut
import numpy as np

m = cut.DeviceMemoryPool()

a= np.ones(2**30,dtype=np.float32)
b=cua.GPUArray(2**30,np.float32,m.allocate)
b.set(a)
```
fails if the bytesize is >=2**32 with:
``` python
LogicError                                Traceback (most recent call last)
<ipython-input-1-4406a447a92f> in <module>
      8 a= np.ones(2**30,dtype=np.float32)
      9 b=cua.GPUArray(2**30,np.float32,m.allocate)
---> 10 b.set(a)

~/dev/pynx-py38-power9-env/lib/python3.8/site-packages/pycuda/gpuarray.py in set(self, ary, async_, stream, **kwargs)
    316
    317         if self.size:
--> 318             _memcpy_discontig(self, ary, async_=async_, stream=stream)
    319
    320     def set_async(self, ary, stream=None):

~/dev/pynx-py38-power9-env/lib/python3.8/site-packages/pycuda/gpuarray.py in _memcpy_discontig(dst, src, async_, stream)
   1507                 drv.memcpy_htod_async(dst.gpudata, src, stream=stream)
   1508             else:
-> 1509                 drv.memcpy_htod(dst.gpudata, src)
   1510         return
   1511

LogicError: cuMemcpyHtoD failed: invalid argument
```

The above error is on a power9 machine, but I also tested on a x86_64 and get the same error. And it only happens when using a `DeviceMemoryPool`..

**Comment by vincefn** [comment]
I went deeper to look into [`wrap_cudadrv.cpp:py_memcpy_htod()`](https://github.com/inducer/pycuda/blob/9fd657a09e8a3d90ce8bb1ad6a48d05fceb97e54/src/wrapper/wrap_cudadrv.cpp#L199) where the actual error is raised, but even printing the values for the `CUdeviceptr` and buffer does not reveal anything obvious. Is the `CUdeviceptr` somehow invalid ?

**Comment by inducer** [comment]
I reopened the issue. I agree that this is super weird. One thing I wonder is whether pooled device allocation force a round-trip through Python `int`s and get broken as part of that? Mabye https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/51 (untested) is more along the lines of what's needed?

**Comment by inducer** [comment]
FYI just updated that a bit... let me know what you find.

**Comment by vincefn** [comment]
I tested the `mem-pool-alloc-inherit-pointer-holder` branch but no difference :-( , still the same error when using a DeviceMemoryPool. 

NB a few compiling errors, need:
``` diff
diff --git a/src/wrapper/mempool.cpp b/src/wrapper/mempool.cpp
index 494a1db..c00e93b 100644--- a/src/wrapper/mempool.cpp
+++ b/src/wrapper/mempool.cpp
@@ -120,7 +120,7 @@ namespace
   class pooled_device_allocation
     : public pycuda::context_dependent,
     public pycuda::pooled_allocation<context_dependent_memory_pool<device_allocator> >,
-    public pointer_holder_base
+    public pycuda::pointer_holder_base   {
     private:
       typedef
@@ -133,7 +133,7 @@ namespace
         : super(p, s)
       { }

-      virtual get_pointer() const
+      virtual CUdeviceptr get_pointer() const
       { return ptr(); }
   };
```

**Comment by vincefn** [comment]
Still investigating. If I look at what is actually allocated in [`device_allocator::allocate(size_t s)`](https://github.com/inducer/pycuda/blob/9fd657a09e8a3d90ce8bb1ad6a48d05fceb97e54/src/wrapper/mempool.cpp#L37) and I print s, I get (using `m=DeviceMemoryPool()`):

1) `cua.GPUArray(2 ** 30 - 1, np.float32, m.allocate)` 
I get `s= 4294967295`. This is slightly off, I would expect `4*(2 ** 30 - 1)=4294967292` but I get `2 ** 32 - 1` instead, but I guess this is part of the custom powers-of-two block allocation from the memory pool so should be OK.

2) `cua.GPUArray(2 ** 30, np.float32, m.allocate)`
I get `s= 1073741823` which is `2**30-1`. Definitely too small.

**Comment by vincefn** [comment]
Ok, found the source of the problem: in [`memory_pool::allocate(size_type size)`](https://github.com/inducer/pycuda/blob/9fd657a09e8a3d90ce8bb1ad6a48d05fceb97e54/src/cpp/mempool.hpp#L165) when asked for size=4294967296 (=2**32) ends up with `alloc_sz=1073741823`.

More specifically in [`memory_pool::alloc_size(size_type size)`](https://github.com/inducer/pycuda/blob/9fd657a09e8a3d90ce8bb1ad6a48d05fceb97e54/src/cpp/mempool.hpp#L112) which has a few bit-shifting operations: the problem either comes from the use of `signed` or the use of `bin_nr_t` or the implicit type for 1 in that function. If I use int64_t instead it seems to give the correct result:
``` diff
       static size_type alloc_size(bin_nr_t bin)
       {
-        bin_nr_t exponent = bin >> mantissa_bits;
-        bin_nr_t mantissa = bin & mantissa_mask;
+        int64_t exponent = bin >> mantissa_bits;
+        int64_t mantissa = bin & mantissa_mask;
 
-        size_type ones = signed_left_shift(1,
-            signed(exponent)-signed(mantissa_bits)
+        size_type ones = signed_left_shift((int64_t)1,
+            int64_t(exponent)-int64_t(mantissa_bits)
             );
         if (ones) ones -= 1;
 
         size_type head = signed_left_shift(
-           (1<<mantissa_bits) | mantissa,
-            signed(exponent)-signed(mantissa_bits));
+           (((int64_t)1)<<mantissa_bits) | mantissa,
+            int64_t(exponent)-int64_t(mantissa_bits));
         if (ones & head)
           throw std::runtime_error("memory_pool::alloc_size: bit-counting fault");
         return head | ones;
         }

```

I think in this case it is `(1<<mantissa_bits)` which was at fault, but the other numbers should be converted to 64 bits for safety.

This is only a quick test so not sure the above diff completely corrects the issue.

**Comment by vincefn** [comment]
I think the following is the minimal diff  (against the `main` branch, I don't know if the`mem-pool-alloc-inherit-pointer-holder ` is useful) which seems to solve the problem, using `boost::uint64_t` which should reasonably portable:

``` diff
diff --git a/src/cpp/mempool.hpp b/src/cpp/mempool.hpp
index be88f13..0441a09 100644
--- a/src/cpp/mempool.hpp
+++ b/src/cpp/mempool.hpp
@@ -51,7 +51,7 @@ namespace PYGPU_PACKAGE
       typedef typename Allocator::size_type size_type;
 
     private:
-      typedef boost::uint32_t bin_nr_t;
+      typedef boost::uint64_t bin_nr_t;
       typedef std::vector<pointer_type> bin_t;
 
       typedef boost::ptr_map<bin_nr_t, bin_t > container_t;
@@ -114,13 +114,13 @@ namespace PYGPU_PACKAGE
         bin_nr_t exponent = bin >> mantissa_bits;
         bin_nr_t mantissa = bin & mantissa_mask;
 
-        size_type ones = signed_left_shift(1,
+        size_type ones = signed_left_shift((bin_nr_t)1,
             signed(exponent)-signed(mantissa_bits)
             );
         if (ones) ones -= 1;
 
         size_type head = signed_left_shift(
-           (1<<mantissa_bits) | mantissa,
+           ((bin_nr_t)1<<mantissa_bits) | mantissa,
             signed(exponent)-signed(mantissa_bits));
         if (ones & head)
           throw std::runtime_error("memory_pool::alloc_size: bit-counting fault");
@@ -352,7 +352,7 @@ namespace PYGPU_PACKAGE
         }
         else
           throw PYGPU_PACKAGE::error(
-              "pooled_device_allocation::free", 
+              "pooled_device_allocation::free",
 #ifdef PYGPU_PYCUDA
               CUDA_ERROR_INVALID_HANDLE
 #endif
```

not fully sure converting `head` and `mantissa` to 64-bit is necessary, maybe only the first argument to `signed_left_shift` needs to be 64-bit.

**Comment by inducer** [comment]
Thanks for working through this and identifying the root cause! https://github.com/inducer/pyopencl/pull/453 fixes and tests this in the context of PyOpenCL. (I started there because its memory pool code had diverged a bit and incorporates a few more things.) I'll create a backport PR for PyCUDA shortly.

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/52 is that backport MR. @vincefn, could you confirm that this addresses the issue for you?

**Comment by vincefn** [comment]
Everything seems OK. Same on the pyopencl side. Thanks !
