### ISSUE TITLE
Pycuda Error on Nvidia DGX2: make_default_context() wasn't able to create a context on any of the 16 detected devices

### ISSUE THREAD

**Issue by philipskokoh** [inducer/pycuda#283]
Hello,

I install pycuda with openGL support a docker container in DGX2 machine, following this guide:
https://wiki.tiker.net/PyCuda/Installation/Linux/
(Note that I use vnc to connect to the DGX machine GUI)

The container I run is based on nvcr.io/nvidia/pytorch:20.02-py3
https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-02.html#rel_20-02

Before I install the pycuda, I install several libraries. Here are my step:
```
apt install freeglut3 freeglut3-dev libxi-dev libxmu-dev libglu1-mesa libglu1-mesa-dev libpci-dev
git clone https://github.com/inducer/pycuda.git
cd pycuda
./configure.py --cuda-root=/usr/local/cuda --cuda-enable-gl
make install
```
The installation is successful. However, when I run `python gl_interop.py` in `pycuda/examples/from-wiki`, I got this error.
```
/opt/pycuda/examples/from-wiki# python gl_interop.py 
Traceback (most recent call last):
  File "gl_interop.py", line 293, in <module>
    main()
  File "gl_interop.py", line 262, in main
    import pycuda.gl.autoinit
  File "/root/miniconda3/envs/ganspace/lib/python3.7/site-packages/pycuda-2020.1-py3.7-linux-x86_64.egg/pycuda/gl/autoinit.py", line 10, in <module>
    context = make_default_context(lambda dev: cudagl.make_context(dev))
  File "/root/miniconda3/envs/ganspace/lib/python3.7/site-packages/pycuda-2020.1-py3.7-linux-x86_64.egg/pycuda/tools.py", line 229, in make_default_context
    "on any of the %d detected devices" % ndevices
RuntimeError: make_default_context() wasn't able to create a context on any of the 16 detected devices
```

I reported this error to nvidia support. They say that the initialization error is not coming from CUDA library. The request is not reaching the library. It could be issue at pycuda.

What would be the possible issue?

Thank you very much!

**Comment by inducer** [comment]
I'm not sure GL interop is supposed to work inside of Docker containers. Does [this](https://github.com/NVIDIA/cuda-samples/tree/master/Samples/simpleGL) CUDA sample work?

**Comment by philipskokoh** [comment]
Hmm... I am using CUDA version 10.2, and the simpleGL folder is not available in v10.2 branch. Any suggestions to test this?

cuda-samples v10.2 branch:
https://github.com/NVIDIA/cuda-samples/tree/v10.2/Samples/simpleGL

**Comment by inducer** [comment]
You should be able to use the new version without an issue.

**Comment by philipskokoh** [comment]
Your are right. Something is not right running the OpenGL.

```
# ./simpleGL 
simpleGL (VBO) starting...

GPU Device 0: "Volta" with compute capability 7.0

CUDA error at simpleGL.cu:421 code=304(cudaErrorOperatingSystem) "cudaGraphicsGLRegisterBuffer(vbo_res, *vbo, vbo_res_flags)" 
CUDA error at simpleGL.cu:433 code=400(cudaErrorInvalidResourceHandle) "cudaGraphicsUnregisterResource(vbo_res)"
```

To give more context, I try to run Ganspace code, and pycuda with openGL is one of the requirement. 
https://github.com/harskish/ganspace/blob/master/SETUP.md
First time to run OpenGL application in DGX machine.

**Comment by inducer** [comment]
At this point, it's unlikely that this has much to do with Pycuda, sorry.
