### ISSUE TITLE
Displaying 6 Failures while running test_driver.py 

### ISSUE THREAD

**Issue by V18006** [inducer/pycuda#284]
Hi,
I am new to CUDA programming, sorry if the error is too long.
I have successfully installed pycuda in jetson TX2 using pip install pycuda
python version is 2.7.15+
pip version is 20.3.4
Ubuntu version is 18.04 LTS
When I run the code python test_driver.py from test folder, it shows 6 failures
`============================================================= test session starts =============================================================
platform linux2 -- Python 2.7.15+, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/coil/pycuda-2021.1, inifile:
collected 33 items                                                                                                                            

test_driver.py .......F.F.F.F................FF.                                                                                        [100%]

================================================================== FAILURES ===================================================================
_________________________________________________ TestDriver.test_additional_primary_context __________________________________________________

args = (<test_driver.TestDriver instance at 0x7fa2687050>,), kwargs = {}
pycuda = <module 'pycuda' from '/home/coil/.local/lib/python2.7/site-packages/pycuda/__init__.pyc'>
ctx = <pycuda._driver.Context object at 0x7fa24c5398>, clear_context_caches = <function clear_context_caches at 0x7fa9754d70>
collect = <built-in function collect>

    def f(*args, **kwargs):
        import pycuda.driver
        # appears to be idempotent, i.e. no harm in calling it more than once
        pycuda.driver.init()
    
        ctx = make_default_context()
        try:
            assert isinstance(ctx.get_device().name(), str)
            assert isinstance(ctx.get_device().compute_capability(), tuple)
            assert isinstance(ctx.get_device().get_attributes(), dict)
>           inner_f(*args, **kwargs)

../../.local/lib/python2.7/site-packages/pycuda/tools.py:462: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_driver.py:727: in test_additional_primary_context
    pctx = drv.Context.get_device().retain_primary_context()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

dev = <pycuda._driver.Device object at 0x7fa24bac20>, name = 'retain_primary_context'

    def device___getattr__(dev, name):
>       return dev.get_attribute(getattr(device_attribute, name.upper()))
E       AttributeError: type object 'device_attribute' has no attribute 'RETAIN_PRIMARY_CONTEXT'

../../.local/lib/python2.7/site-packages/pycuda/driver.py:180: AttributeError
__________________________________________________________ TestDriver.test_mempool_2 __________________________________________________________

args = (<test_driver.TestDriver instance at 0x7fa24d7b90>,), kwargs = {}
pycuda = <module 'pycuda' from '/home/coil/.local/lib/python2.7/site-packages/pycuda/__init__.pyc'>
ctx = <pycuda._driver.Context object at 0x7fa1a5a758>, clear_context_caches = <function clear_context_caches at 0x7fa9754d70>
collect = <built-in function collect>

    def f(*args, **kwargs):
        import pycuda.driver
        # appears to be idempotent, i.e. no harm in calling it more than once
        pycuda.driver.init()
    
        ctx = make_default_context()
        try:
            assert isinstance(ctx.get_device().name(), str)
            assert isinstance(ctx.get_device().compute_capability(), tuple)
            assert isinstance(ctx.get_device().get_attributes(), dict)
>           inner_f(*args, **kwargs)

../../.local/lib/python2.7/site-packages/pycuda/tools.py:462: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_driver.TestDriver instance at 0x7fa24d7b90>

    @mark_cuda_test
    def test_mempool_2(self):
        from pycuda.tools import DeviceMemoryPool
        from random import randrange
        pool = DeviceMemoryPool()
    
        for i in range(2000):
            s = randrange(1 << 31) >> randrange(32)
            bin_nr = pool.bin_number(s)
            asize = pool.alloc_size(bin_nr)
    
            assert asize >= s, s
            assert pool.bin_number(asize) == bin_nr, s
>           assert asize < asize * (1 + 1 / 8)
E           assert 3 < (3 * (1 + (1 / 8)))

test_driver.py:681: AssertionError
____________________________________________________ TestDriver.test_register_host_memory _____________________________________________________

args = (<test_driver.TestDriver instance at 0x7fa2709368>,), kwargs = {}
pycuda = <module 'pycuda' from '/home/coil/.local/lib/python2.7/site-packages/pycuda/__init__.pyc'>
ctx = <pycuda._driver.Context object at 0x7fa1a5a410>, clear_context_caches = <function clear_context_caches at 0x7fa9754d70>
collect = <built-in function collect>

    def f(*args, **kwargs):
        import pycuda.driver
        # appears to be idempotent, i.e. no harm in calling it more than once
        pycuda.driver.init()
    
        ctx = make_default_context()
        try:
            assert isinstance(ctx.get_device().name(), str)
            assert isinstance(ctx.get_device().compute_capability(), tuple)
            assert isinstance(ctx.get_device().get_attributes(), dict)
>           inner_f(*args, **kwargs)

../../.local/lib/python2.7/site-packages/pycuda/tools.py:462: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_driver.TestDriver instance at 0x7fa2709368>

    @mark_cuda_test
    def test_register_host_memory(self):
        if drv.get_version() < (4,):
            from py.test import skip
    
            skip("register_host_memory only exists on CUDA 4.0 and later")
    
        import sys
    
        if sys.platform == "darwin":
            from py.test import skip
    
            skip("register_host_memory is not supported on OS X")
    
        a = drv.aligned_empty((2 ** 20,), np.float64)
>       a_pin = drv.register_host_memory(a)
E       LogicError: cuMemHostRegister failed: operation not supported

test_driver.py:931: LogicError
________________________________________________________ TestDriver.test_gpuarray_cai _________________________________________________________

args = (<test_driver.TestDriver instance at 0x7fa24ee2d8>,), kwargs = {}
pycuda = <module 'pycuda' from '/home/coil/.local/lib/python2.7/site-packages/pycuda/__init__.pyc'>
ctx = <pycuda._driver.Context object at 0x7fa1a5a500>, clear_context_caches = <function clear_context_caches at 0x7fa9754d70>
collect = <built-in function collect>

    def f(*args, **kwargs):
        import pycuda.driver
        # appears to be idempotent, i.e. no harm in calling it more than once
        pycuda.driver.init()
    
        ctx = make_default_context()
        try:
            assert isinstance(ctx.get_device().name(), str)
            assert isinstance(ctx.get_device().compute_capability(), tuple)
            assert isinstance(ctx.get_device().get_attributes(), dict)
>           inner_f(*args, **kwargs)

../../.local/lib/python2.7/site-packages/pycuda/tools.py:462: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_driver.TestDriver instance at 0x7fa24ee2d8>

    @mark_cuda_test
    def test_gpuarray_cai(self):
        a = np.zeros(10, dtype=np.float32)
        a_g = gpuarray.to_gpu(a)
>       cai = a_g.__cuda_array_interface__
E       AttributeError: 'GPUArray' object has no attribute '__cuda_array_interface__'

test_driver.py:156: AttributeError
__________________________________________________________ test_pointer_holder_base ___________________________________________________________

    def test_pointer_holder_base():
>       alloc = WrappedAllocation(drv.mem_alloc(1024))

test_driver.py:1075: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_driver.WrappedAllocation object at 0x7fa1a62e10>, wrapped = <pycuda._driver.DeviceAllocation object at 0x7fa1a5bde0>

    def __init__(self, wrapped):
        self.wrapped = wrapped
>       super().__init__()
E       TypeError: super() takes at least 1 argument (0 given)

test_driver.py:1068: TypeError
_____________________________________________________________ test_pass_cai_array _____________________________________________________________

    def test_pass_cai_array():
        dtype = np.int32
        size = 1024
        np_array = np.arange(size, dtype=dtype)
        cai_array = CudaArrayInterfaceImpl(size, np_array.itemsize, np_array.dtype)
    
        mod = SourceModule(
            """
        __global__ void gpu_arange(int *x)
        {
          const int i = threadIdx.x;
          x[i] = i;
        }
        """
        )
    
        gpu_arange = mod.get_function("gpu_arange")
>       gpu_arange(cai_array, grid=(1,), block=(size, 1, 1))

test_driver.py:1122: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../.local/lib/python2.7/site-packages/pycuda/driver.py:437: in function_call
    handlers, arg_buf = _build_arg_buf(args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<test_driver.CudaArrayInterfaceImpl instance at 0x7fa25a6b48>,)

    def _build_arg_buf(args):
        handlers = []
    
        arg_data = []
        format = ""
        for i, arg in enumerate(args):
            if isinstance(arg, np.number):
                arg_data.append(arg)
                format += arg.dtype.char
            elif isinstance(arg, (DeviceAllocation, PooledDeviceAllocation)):
                arg_data.append(int(arg))
                format += "P"
            elif isinstance(arg, ArgumentHandler):
                handlers.append(arg)
                arg_data.append(int(arg.get_device_alloc()))
                format += "P"
            elif isinstance(arg, np.ndarray):
                if isinstance(arg.base, ManagedAllocationOrStub):
                    arg_data.append(int(arg.base))
                    format += "P"
                else:
                    arg_data.append(arg)
                    format += "%ds" % arg.nbytes
            elif isinstance(arg, np.void):
                arg_data.append(_my_bytes(_memoryview(arg)))
                format += "%ds" % arg.itemsize
            else:
                try:
                    gpudata = np.uintp(arg.gpudata)
                except AttributeError:
>                   raise TypeError("invalid type on parameter #%d (0-based)" % i)
E                   TypeError: invalid type on parameter #0 (0-based)

../../.local/lib/python2.7/site-packages/pycuda/driver.py:212: TypeError
==================================================== 6 failed, 27 passed in 18.83 seconds =====================================================`

**Comment by inducer** [comment]
You're running the tests from one version of pycuda on a different version of pycuda's installed bits. There's no reason this should work.
