### ISSUE TITLE
LogicError: cuMemHostAlloc failed: context is destroyed

### ISSUE THREAD

**Issue by thuzhf** [inducer/pycuda#285]
The following code doesn't work:
```python3
import pycuda.driver as cuda
import torch

cuda.init()
d0 = cuda.Device(0)
ctx0 = d0.make_context()

# why will this line lead to ctx0 being destroyed?
torch.ones(1, device=1)

# this line will report: LogicError: cuMemHostAlloc failed: context is destroyed
cuda.pagelocked_empty([3,4], 'float32')
```
The last line will report: `LogicError: cuMemHostAlloc failed: context is destroyed`
But if you comment `torch.ones(1, device=1)`, the last line will work. 

Why? Is it a bug?

**Comment by thuzhf** [comment]
I checked the example, but I don't think it's very much related. What I want to achieve is use the API to create page-locked memory or post-register host-allocated memory to be page-locked. I don't need to execute pycuda kernel on torch tensors.
My context creation is similar with the code within `pycuda.autoinit`, and it is because I need to create context on different devices so that I don't use `import pycuda.autoinit` directly. I need to manually create different context on different devices. The code within `pycuda.autoinit` is as follows:
https://github.com/inducer/pycuda/blob/7c759be651a6e03c6b68eac2bda12b0eaacb9564/pycuda/autoinit.py#L1-L24
And `make_default_context` is defined as follows:
https://github.com/inducer/pycuda/blob/7c759be651a6e03c6b68eac2bda12b0eaacb9564/pycuda/tools.py#L178-L229

I actually have read the above two code and your documentation to learn how to create context. Could you please tell me what's wrong with my context creation?

**Comment by inducer** [comment]
You need to retain the device context if you would like to exchange data with other code that uses the runtime API.

**Comment by thuzhf** [comment]
I see, but how can I retain the device context? Could you please tell me or refer me to some documentation on how to do this? I cannot find related topics in your documentation. It seems to be related to `pycuda.driver.Context.push/pop` but I am not very sure and don't know how to write code to retain the device context correctly.

**Comment by inducer** [comment]
https://documen.tician.de/pycuda/driver.html#pycuda.driver.Device.retain_primary_context

**Comment by thuzhf** [comment]
Thanks!
