### ISSUE TITLE
Equivalent to `np.asfortranarray`

### ISSUE THREAD

**Issue by dsuess** [inducer/pycuda#291]
I could not find a way to convert an array into one with a different order. In numpy this is done using `np.ascontiguousarray` and `np.asfortranarray`. 

I tried the following hacky version with no success since the returned array does have the elements in the wrong order:

```
def cuasfortranarray(array):
    result = gpuarray.empty_like(array, order="F")
    result[:] = array
    return result
```

**Comment by inducer** [comment]
Thanks for the report. That slice assignment should definitely error out (#292). What you're effectively asking for is a generic, efficient transpose. For 2D arrays, there's a solution (an even an [example](https://github.com/inducer/pycuda/blob/main/examples/from-wiki/matrix_transpose.py)). A general solution is quite a bit harder, and not currently implemented. You might be interested in https://github.com/inducer/loopy though, which makes writing codes like this a bit easier. See (`loopy.make_copy_kernel` and [the transpose test](https://github.com/inducer/loopy/blob/262f05ce5ea2775cdf6e8732316cb4d05e9e9c96/test/test_linalg.py#L125-L154)).

**Comment by dsuess** [comment]
Thanks for your quick answer! Looks like I'll by going with loopy for this
