### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [inducer/pycuda#294]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine test/test_gpuarray.py and observe `substraction`, however expect to see `subtraction`.
- Examine pycuda/cuda/pycuda-helpers.hpp and observe `supprt`, however expect to see `support`.
- Examine examples/from-wiki/mandelbrot_interactive.py and observe `rigth`, however expect to see `right`.
- Examine aksetup_helper.py and observe `prefered`, however expect to see `preferred`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/pycuda/pull/new/bugfix_typos

Thanks.

**Comment by inducer** [comment]
Sure, go ahead and make the PR.

**Comment by timgates42** [comment]
Thanks @inducer added #295
