### ISSUE TITLE
Two comments:

### ISSUE THREAD

**Issue by hao6699** [inducer/pycuda#296]
Two comments:
- Do *not* use `autoinit`.
- You need to `push` the primary context onto the context stack to activate it.

_Originally posted by @inducer in https://github.com/inducer/pycuda/issues/242#issuecomment-692191610_

I am confused abount how to push the primary context onto the context stack to activate it? Can you show me the code? Thanks very much !!!

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
