### ISSUE TITLE
make_context exit without any log

### ISSUE THREAD

**Issue by paradisebee** [inducer/pycuda#308]
When I tried calling make_context(), it exit without any error infos. 
What is the problem?

OS:        Win 10
GPU:      RTX 2070
Env:       python 3.6.12, Anaconda
pycuda: pycuda 2021.1 from pypi

simple test:

 (dl) D:\labelling>python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
\>>> import pycuda.driver as cuda
\>>> cuda.init()
\>>> dev = cuda.Device(0)
\>>> dev.name()
'GeForce RTX 2070 SUPER'
\>>> dev.make_context()

(dl) D:\labelling>

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
