### ISSUE TITLE
Combine Cuda IPC wth Direct Access

### ISSUE THREAD

**Issue by eedalong** [inducer/pycuda#312]
I have 2 GPUs and they are under the same PCIe Switch. When I enable P2P access and allocate memory blocks on device1 and device0, I can access device1's memory block in kernels launched on device 0 within current process.
I wander whether a cuda IPC memory handle, allocated on device1 from another process, can somehow be directly accessed in kernel launched on device0 within current process.

**Comment by inducer** [comment]
Isn't that what's controlled by the `LAZY_ENABLE_PEER_ACCESS` flag passed to the `IPCMemoryHandle` constructor?

See
- https://documen.tician.de/pycuda/driver.html?highlight=ipc#pycuda.driver.IPCMemoryHandle
- https://documen.tician.de/pycuda/driver.html?highlight=ipc#pycuda.driver.ipc_mem_flags.LAZY_ENABLE_PEER_ACCESS

**Comment by eedalong** [comment]
Yes, It works, Thx! @inducer
