### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yunweilu** [inducer/pycuda#313]
gcc version-4.9.3
Ubuntu version -16.04

I'm pretty sure my cuda-path is the right one.
I use dpkg -L cuda to make sure the position and I got "/usr/share/doc/cuda". And I try "python configure.py --cuda-root=/usr/share/doc/cuda". 
 
The error is as followed.
Error: command 'gcc' failed with exit status 1

I have same command output with this case #301

**Comment by inducer** [comment]
Your version of gcc is too old. (Ubuntu 16.x is five years old at this point!)
