### ISSUE TITLE
Type subscription requires python >= 3.9

### ISSUE THREAD

**Issue by pierrepaleo** [inducer/pycuda#382]
**Describe the bug**

Upon fresh installation of pycuda (built from main branch commit f9c821b), importing `ElementwiseKernel` crashes for `python < 3.9`.

**To Reproduce**

```python
from pycuda.elementwise import ElementwiseKernel
```

crashes for python < 3.9 with `TypeError: Type subscription requires python >= 3.9`

**Expected behavior**

No crash on import.

It seems to be caused by 1dcaf262 with `_get_real_dtype()`. 

I'd be glad to submit a PR, can you just confirm that pycuda is supposed to support python < 3.9 ? (Otherwise the `pyproject.toml` file will have to be updated).

**Comment by inducer** [comment]
Thanks for the report. https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/83 should take care of it.
