### ISSUE TITLE
Compiler error when building for NVidia Jetson Orin (aarch64) platform with CUDA 11.8

### ISSUE THREAD

**Issue by RedBreadcat** [inducer/pycuda#415]
**Describe the bug**
When attempting to build PyCuda 2022.2.2 on an NVidia Orin, I get a compiler error related to `CU_TARGETC_OMPUTE_20` and `CU_TARGET_COMPUTE_21`. I'm guessing that the #ifdefs for the CU_TARGET_COMPUTE_* enum values in src/wrapper/wrap_cudadrv.cpp were chosen based off x86-64 CUDA, however it seems that aarch64's cuda.h is different?

**To Reproduce**
`pip3 install pycuda --user`, or download from source and build.

**Expected behavior**
pycuda builds and installs. However, there's the following compiler error:
```
src/wrapper/wrap_cudadrv.cpp:1034:26: error: ‘CU_TARGET_COMPUTE_20’ was not declared in this scope; did you mean ‘CU_TARGET_COMPUTE_80’?
   1034 |     .value("COMPUTE_20", CU_TARGET_COMPUTE_20)
		|                          ^~~~~~~~~~~~~~~~~~~~
		|                          CU_TARGET_COMPUTE_80
src/wrapper/wrap_cudadrv.cpp:1037:26: error: ‘CU_TARGET_COMPUTE_21’ was not declared in this scope; did you mean ‘CU_TARGET_COMPUTE_61’?
   1037 |     .value("COMPUTE_21", CU_TARGET_COMPUTE_21)
		|                          ^~~~~~~~~~~~~~~~~~~~
		|                          CU_TARGET_COMPUTE_61
```
I've attached the system's cuda.h: [cuda_h.zip](https://github.com/inducer/pycuda/files/11786036/cuda_h.zip)
In this header, the enum `CUjit_target_enum` starts at `CU_TARGET_COMPUTE_30`, hence the error.
Here's where I installed CUDA 11.8 from: https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=aarch64-jetson&Compilation=Native&Distribution=Ubuntu&target_version=20.04&target_type=deb_local

If I comment out the problematic lines in wrap_cudadrv.cpp then it builds just fine.

**Environment:**
 - Platform: NVidia Orin
 - OS: Ubuntu 20.04
 - CUDA version: 11.8
 - CUDA driver version: N/A? The Nvidia L4T version is 35.3.1
 - PyCUDA version: tags/v2022.2.2
 - Python version: 3.8.16

**Comment by inducer** [comment]
Thanks for the report. This isn't ideal. I have an x86-64 CUDA 11.8 header sitting around, and diffing them shows the removal of these enum values as the only difference... and I don't think the preprocessor can tell us whether an enum value is defined. On the upside, these are slated for removal in CUDA 12, so I've gone ahead and "pre-poned" that removal to 11.8:

https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/91

If you've got a better idea, I'd be all ears.

**Comment by RedBreadcat** [comment]
I did some searching, and it seems like there are a couple of wells to tell whether an enum value is defined.
There's this way, which unfortunately requires manually creating a couple of functions for each enum value you want to check: https://gist.github.com/forGGe/53ea04fd14196dd3bb55237a0252a18c

There's also magic_enum's approach, which seems to work across all possible enum values, but I wasn't able to understand it: https://github.com/Neargye/magic_enum/blob/8107ceb0fa44d4298ba81b85a13f7078e7e53791/include/magic_enum.hpp#L1333

You may or may not consider them overkill, I'm not sure.
