### ISSUE TITLE
ftbfs with Python 3.12, making use of the removed imp and distutils modules

### ISSUE THREAD

**Issue by anbe42** [inducer/pycuda#429]
as reported on Debian: https://bugs.debian.org/1055702

**Comment by inducer** [comment]
Works for me with the version in git. I suspect all that's needed is a new release. Let me do that.

**Comment by inducer** [comment]
https://pypi.org/project/pycuda/2023.1/

**Comment by inducer** [comment]
Feel free to reopen/comment if that didn't do the trick.
