### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by lahwaacz** [inducer/pycuda#442]
The [Installation page](https://documen.tician.de/pycuda/install.html) in the documentation only links to the wiki, which returns 404 error: http://wiki.tiker.net/PyCuda/Installation

Also the "About" section of the [github repo](https://github.com/inducer/pycuda) links to http://mathema.tician.de/software/pycuda which gives 404 as well.

**Comment by inducer** [comment]
That was quick! Those were just moving between servers. Should be fine now, LMK if not.

**Comment by lahwaacz** [comment]
It's still 404 for me... Maybe I just have a bad luck :shrug:

**Comment by inducer** [comment]
Try hard-reloading. (Hold Shift and press reload on your browser.) LMK if it doesn't start working soon.

**Comment by lahwaacz** [comment]
Still nothing. I'm using [qutebrowser](https://www.qutebrowser.org/) and it shows only "404 Not Found nginx/1.26.0". Same with curl:

```
$ curl http://wiki.tiker.net/PyCuda/Installation
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.26.0</center>
</body>
</html>
```

Interestingly, the page loads fine in Firefox and Chrome. Are you doing some weird user-agent filtering? If so, please don't :smile:

**Comment by inducer** [comment]
> Are you doing some weird user-agent filtering? If so, please don't 😄

I'm not! That's not the kind of person I am. :slightly_smiling_face: 

Joking aside, I think I found the issue. It works over IPv6, but it fails over IPv4. Observe:
```
$ curl http://wiki.tiker.net/PyCuda/Installation
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.26.0</center>
</body>
</html>
$ curl -4 http://wiki.tiker.net/PyCuda/Installation
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.26.0</center>
</body>
</html>
```

Should be all better now. It turns out I upgraded versions of nginx (a web server) as part of the server move, and there was a behavior change that triggered this.

**Comment by inducer** [comment]
And thanks for sticking this out! Without your persistence, this probably would have taken another good while to discover.
