### ISSUE TITLE
Compatibility with numpy 2

### ISSUE THREAD

**Issue by vincefn** [inducer/pycuda#450]
Hi @inducer I guess this is not a surprise, but pycuda does not work with numpy>=2.

Is there any plan to support it ? Something alike [what was done for pyopencl](https://github.com/inducer/pyopencl/pull/720) ?

attn @pierrepaleo

**Comment by inducer** [comment]
Yes, I would definitely like to do that. Help welcome, otherwise I'll likely get to it sometime.

**Comment by vincefn** [comment]
Hi Andreas, I took a shot at this, using the pyopencl changes as a base.
I've pushed changes:
* https://github.com/vincefn/compyte/tree/numpy2
* https://github.com/vincefn/pycuda/tree/numpy2

Now all pycuda tests are passing (with python 12 and numpy 2.0, and cuda 11.8) , except `TestDriver.test_register_host_memory` which fails with `ValueError: Cannot set the NumPy array 'base' dependency more than once`.

I'll add two PR against pycuda and compyte, but this needs a close look - I'm not a numpy C API expert at all...

PS: there are other failures when using python 12.2, when using textures - I guess it's unrelated to numpy 2 ?

**Comment by pierrepaleo** [comment]
Thanks! I did [an (incomplete) attempt a while ago](https://github.com/inducer/pycuda/compare/main...pierrepaleo:pycuda:numpy2), not sure that's useful, I did not see the changes in pyopencl at the time.

**Comment by inducer** [comment]
#451 should have addressed this.
