### ISSUE TITLE
No support for Python 3.8

### ISSUE THREAD

**Issue by denniswittich** [inducer/pycuda#454]
Since version [2024.1.1](https://github.com/inducer/pycuda/compare/v2024.1...v2024.1.1) you require numpy version >= 2.0. If I get it right, the setup.py says you support python 3.8 (python_requires="~=3.8"). However, since [Numpy 1.25](https://numpy.org/news/) the minimum python version is 3.9. This results in a error message when trying to install pycuda with python 3.8.

**Comment by inducer** [comment]
I don't see anything specific to numpy 2 in #451, so I've just bumped the numpy requirement to 1.24, which should support 3.8. I've also yanked the 2024.1.1 release.

https://pypi.org/project/pycuda/2024.1.2/
