### ISSUE TITLE
Cannot pip install pycuda

### ISSUE THREAD

**Issue by kerkilchoi** [inducer/pycuda#55]
I have an issue installing pyCUDA using "pip install pycuda."
I am running Mac OS X Mavericks 10.9. I installed CUDA 6.5 SDK for Mac 10.9. Xcode 5.1.1 and the developer tools are also installed. My Nvidia graphics is NVIDIA GeForce GTX 680MX (2GB memory).

The errors I got are

```
ld: library not found for -lcuda
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang++' failed with exit status 1
```

What is causing this issue? Should I configure on top of using "pip install pycuda?"
Please guide me to fixing the issue. Thanks.

**Comment by tibbon** [comment]
Are there any relevant changes for newer versions of OS X? The docs there go through 10.9.

**Comment by inducer** [comment]
Please don't use the bug tracker for support issues. That's what the maiing list is for. Investigate what a backtrace is.

**Comment by tibbon** [comment]
I know what a backtrace is. There's a real issue with the software not running, and the documentation not being up to date. I'll use the mailing list, but I don't understand the lack of community support and hostility here.

**Comment by inducer** [comment]
Stuffing multiple replies (here and #92) that don't add a lot of relevant information (such as a backtrace) into likely unrelated reports on the wrong forum (bug tracker vs ML) is not going to get you welcomed with open arms.
