### ISSUE TITLE
gpuarray.reshape does not accept "-1"

### ISSUE THREAD

**Issue by untom** [inducer/pycuda#62]
Numpy ndarrays accept "-1" as value for their `reshape` operation, which essentially stands for "fill in whatever is left over". This is useful to e.g. turn row-vectors into column-vectors:

    x.reshape(-1, 1)    # this is now a column-vector
    x.reshape(-1)   # essentially the same as x.ravel()

I use this feature often and find it very convenient, however PyCUDA does currently not support this. It would be nice if this could be added.

**Comment by inducer** [comment]
Agreed, I find that super-handy, too. I'd love to take a patch if you've got the time.
