### ISSUE TITLE
PyCUDA working only with cuda-6.0

### ISSUE THREAD

**Issue by adityaatluri** [inducer/pycuda#64]
Hi,
I was trying to install pycuda with different toolkits. It is working fine only with cuda-6.0. I tested with cuda-6.5 and cuda-7.0 also. It is throwing these errors. These are pertaining to cuda driver changes. Does changes need to be done for pycuda repo (this repo)?

/usr/local/lib/python2.7/dist-packages/pycuda-2014.1-py2.7-linux-x86_64.egg/pycuda/_driver.so: undefined symbol: cuMemHostRegister_v2

**Comment by inducer** [comment]
That's generally a sign that the headers that you're compiling against (which come with the toolkit) do not match your libcuda.so (which comes with the driver package).

**Comment by adityaatluri** [comment]
I used ./configure.py --cuda-root=/usr/local/cuda-6.0. If I want to do with 6.5 or higher, what arguments do I have to pass?
