### ISSUE TITLE
cc1plus: error: unrecognized command line option "-Wp"

### ISSUE THREAD

**Issue by adityaatluri** [inducer/pycuda#65]
Hi,
I was trying to run https://gist.github.com/adityaatluri/8828fdf47aa005a0d49d on CentOS. CUDA v6.0, Python 2.6. The string is coming from nvcc_toolchain

**Comment by WayneRH** [comment]
Is this fixed? I got the same error when I install gputools on rhel6. 
..........
** libs
** arch -
/usr/local/cuda-7.5/bin/nvcc -c -Xcompiler "-fpic -I/usr/local/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic" -I. -I"/usr/local/cuda-7.5/include" -I"/usr/lib64/R/include" rinterface.cu -o rinterface.o
cc1plus: error: unrecognized command line option "-Wp"

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.
