### ISSUE TITLE
Multi-gpu Peer Access inconsistent

### ISSUE THREAD

**Issue by gforsyth** [inducer/pycuda#71]
This may be an oversight on my end, but I'm having trouble with enabling peer access though PyCUDA.  I have a K40 and a K20 -- the simpleP2P program included with the cuda toolkit passes its test but in PyCUDA, I get a different result.

the following snippet throws an exception on the last line

```Python
from pycuda import driver
driver.init()
k40 = driver.Device(0)
k20 = driver.Device(1)

print "K40 can access K20: {}".format(k40.can_access_peer(k20))
print "K20 can access K40: {}".format(k20.can_access_peer(k40))

k4ctx = k40.make_context()
k2ctx = k20.make_context()

k2ctx.enable_peer_access(k4ctx)
k4ctx.enable_peer_access(k2ctx)
```

```
---> 13 k4ctx.enable_peer_access(k2ctx)
LogicError: cuCtxEnablePeerAccess failed: peer access is not supported between these two devices
```

**Comment by inducer** [comment]
`enable_peer_access` is a static method, so you need to make `k4ctx` current before you enable peer access to `k2ctx`.
