### ISSUE TITLE
GPUArray creation fails for shapes containing type long

### ISSUE THREAD

**Issue by lebedov** [inducer/pycuda#86]
Using pycuda 2015.1.3 with Python 2.7.10, the following raises an `AssertionError`:

```
import numpy as np
import pycuda.autoinit
import pycuda.gpuarray as gpuarray

x_gpu = gpuarray.empty(long(3), np.float32)
```

The failure occurs at line 170 in gpuarray.py:

```
assert isinstance(shape, (int, int, np.integer))
```

Leaving aside the question as to why int appears twice in the above check, I suggest modifying it to

```
import numbers
...
assert isinstance(shape, numbers.Integral)
```
which seems to accept int, long, and the various numpy integer types.

(Context: the above might be the cause of the skcuda issue reported [here](https://github.com/lebedov/scikit-cuda/issues/131).)

**Comment by lebedov** [comment]
Note also that the shape of a numpy array can contain long values on Windows (see https://github.com/numpy/numpy/issues/5809) and therefore can run into this problem.

**Comment by inducer** [comment]
Thanks! TIL about `numbers`.
