### ISSUE TITLE
trouble installing pycuda

### ISSUE THREAD

**Issue by great-thoughts** [inducer/pycuda#92]
I am finding some trouble installing pycuda. When I run 'python test_driver.py',  I get the following: 
E           CompileError: nvcc compilation of /var/folders/8k/4dgjf1252rvdrqmb63f_w5bm0000gn/T/tmpFIgNjO/kernel.cu failed
E           [command: nvcc --cubin -arch sm_30 -m64 -I/Users/mas/PycharmProjects/kaggle-ndsb/env5/lib/python2.7/site-packages/pycuda-2015.1.3-py2.7-macosx-10.10-intel.egg/pycuda/cuda kernel.cu]
E           [stderr:
E           nvcc fatal   : The version ('70000') of the host compiler ('Apple clang') is not supported
E           ]

../../env5/lib/python2.7/site-packages/pycuda-2015.1.3-py2.7-macosx-10.10-intel.egg/pycuda/compiler.py:137: CompileError
================ 19 failed, 6 passed, 2 skipped in 2.40 seconds ================

I have a mac and my mvcc version is release 7.0, V7.0.27

**Comment by inducer** [comment]
The cuda toolkit you installed is not compatible with your OS. Toolkit 7.5 is current IIRC.

**Comment by tibbon** [comment]
I get a segmentation fault when running the `test_driver.py` file. No usable errors otherwise.

**Comment by inducer** [comment]
Please don't use the bug tracker for support issues. That's what the maiing list is for. Investigate what a backtrace is.
