### ISSUE TITLE
managed_zeros_like calls pagelocked_empty_like

### ISSUE THREAD

**Issue by bmerry** [inducer/pycuda#96]
Something I just happened to notice while browsing the code - I haven't actually tested whether it is an issue:
```python
def managed_zeros_like(array, mem_flags=0):
    result = pagelocked_empty_like(array, mem_flags)
    result.fill(0)
    return result
```
in `pycuda/driver.py`. I assume it should call `managed_empty_like` rather than `pagelocked_empty_like`.

**Comment by inducer** [comment]
Fixed in bda42286ca19569cbf674b02c86682c7d86ba4dd. Thanks for the report!
