### ISSUE TITLE
libcuda not always in the expected location

### ISSUE THREAD

**Issue by jacksonloper** [inducer/pycuda#98]
At least for the version of the cuda7.5 toolkit that ships with the docker image nvidia/cuda, the file libcuda.so is to be found in a goofy subdirectory of the regular lib directory, called "stubs."  In order for me to get things working, I needed to use a configuration command like

    python configure.py --ldflags="-L/usr/local/cuda/lib64/stubs" --cuda-root=/usr/local/cuda-7.5

It would be cool if the configure script could figure that out by itself.

More generally, the wiki says that pycuda was built against the beta of the 2.0 toolkit, and that the latest version of pycuda is 2.2.  Which I guess means the last time it was edited was March 2009.  What version of the toolkit are you developers actually building against?

**Comment by inducer** [comment]
Are `libcudart.so` and `llibcurand.so` also in the `stubs` directory? The wiki is old (I'd appreciate help modernizing)--feel free to delete stuff that's stale. I build and test against the latest driver release that's in Debian, which is 352.55. The toolkit version actually matters fairly little to PyCUDA, but I've got 7.0.

**Comment by jacksonloper** [comment]
Cool.  

These are the libs I have in stubs

    libcublas.so  libcuda.so  libcufft.so  libcufftw.so  libcurand.so  
    libcusolver.so  libcusparse.so  libnppc.so  libnppi.so  libnpps.so  libnvrtc.so

**Comment by inducer** [comment]
Thanks for your report!
