### ISSUE TITLE
Pycuda [Error cuda.lib not found ] and link.exe exit with code 1181 ? 

### ISSUE THREAD

**Issue by roxxup** [inducer/pycuda#99]
i get error while installing pycuda on windows 64 bit with cuda 5.0 installed

**Comment by pwalsh0** [comment]
Cuda and a compatible c++ compiler are required.

Easiest way: Install vs2013 community edition (free), install cuda sdk 7.5.

Cuda 5.0 will only work with older versions of VS.

**Comment by inducer** [comment]
@roxxup This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

@pwalsh0 Thanks for the hints.
